const mockAgents = [
  // === 网站/建站 (Web) ===
  { id: '1', name: '网站设计师', slug: 'web-designer', division: '网站', emoji: '🌐', vibe: '设计美观易用的网站', description: '精通网站设计、页面布局、视觉设计', detail: '专注于网站整体视觉设计，精通HTML5/CSS3，能设计响应式、美观、用户体验优秀的网站页面。擅长配色、排版、图片处理、交互动效。' },
  { id: '2', name: '建站专家', slug: 'website-builder', division: '网站', emoji: '🏗️', vibe: '快速搭建专业网站', description: '精通WordPress/Shopify/Wix等建站平台', detail: '熟练使用各类建站平台和CMS系统，能快速搭建企业官网、电商网站、博客、落地页等。精通主题定制、插件开发、SEO优化。' },
  { id: '3', name: '网站开发工程师', slug: 'web-developer', division: '网站', emoji: '💻', vibe: '构建高性能网站系统', description: '精通网站前后端开发技术', detail: '具备完整的网站开发能力，精通HTML/CSS/JavaScript，熟练使用React/Vue等框架，能独立完成从设计到部署的网站开发全流程。' },
  { id: '4', name: '电商网站专家', slug: 'ecommerce-website-expert', division: '网站', emoji: '🛒', vibe: '打造高转化的电商网站', description: '精通电商网站设计与开发', detail: '专注于电商平台开发，精通商品管理、购物车、支付系统、订单处理等核心功能。熟悉Shopify、WooCommerce、Magento等电商平台。' },
  { id: '5', name: '网站SEO优化师', slug: 'website-seo-specialist', division: '网站', emoji: '🔍', vibe: '让网站获得更多自然流量', description: '精通网站SEO优化和搜索引擎排名', detail: '专注于网站搜索引擎优化，精通关键词研究、站内优化、技术SEO、内容策略，能有效提升网站在搜索引擎中的排名和流量。' },
  { id: '6', name: '网站性能优化师', slug: 'website-performance-optimizer', division: '网站', emoji: '⚡', vibe: '让网站加载更快体验更好', description: '精通网站性能分析和优化', detail: '专注于网站性能优化，精通Core Web Vitals、页面加载速度优化、图片优化、CDN配置、缓存策略，能显著提升网站性能和用户体验。' },
  { id: '7', name: '网站安全专家', slug: 'website-security-specialist', division: '网站', emoji: '🛡️', vibe: '保护网站免受攻击', description: '精通网站安全防护和漏洞修复', detail: '专注于网站安全，精通SSL证书配置、防火墙设置、SQL注入防护、XSS防护、DDoS防御，能全面保障网站安全运行。' },
  { id: '8', name: '网站内容策划', slug: 'website-content-planner', division: '网站', emoji: '📝', vibe: '为网站创作优质内容', description: '精通网站内容策划和文案写作', detail: '专注于网站内容策划，精通文案写作、内容结构设计、用户故事撰写，能为网站创作吸引用户、促进转化的优质内容。' },

  // === 工程 (Engineering) ===
  { id: '9', name: '前端开发工程师', slug: 'frontend-developer', division: '工程', emoji: '🎨', vibe: '打造美观、高性能的用户界面', description: '精通React/Vue/Angular等现代前端框架', detail: '专注于构建响应式Web应用，熟练掌握HTML5/CSS3/JavaScript/TypeScript，精通组件化开发、状态管理、性能优化，能独立完成从原型到部署的完整前端项目。' },
  { id: '10', name: '后端开发工程师', slug: 'backend-developer', division: '工程', emoji: '⚙️', vibe: '构建稳定可靠的服务器端系统', description: '精通Node.js/Python/Go等后端技术', detail: '负责设计和实现RESTful API、微服务架构、数据库设计与优化，具备高并发、分布式系统开发经验，熟悉Docker/Kubernetes等容器化技术。' },
  { id: '11', name: '全栈开发工程师', slug: 'fullstack-developer', division: '工程', emoji: '🔥', vibe: '端到端贯通的技术多面手', description: '前后端技术栈全覆盖', detail: '具备从数据库设计到用户界面的完整开发能力，精通前后端主流技术栈，能独立负责完整产品的技术实现，善于快速原型开发和迭代。' },
  { id: '4', name: '移动端开发工程师', slug: 'mobile-developer', division: '工程', emoji: '📱', vibe: '创造极致的移动体验', description: '精通iOS/Android跨平台开发', detail: '熟练掌握Swift/Kotlin/Flutter/React Native等移动开发技术，精通移动端性能优化、离线存储、推送通知等功能实现，能开发高质量的原生和跨平台应用。' },
  { id: '5', name: 'DevOps工程师', slug: 'devops-engineer', division: '工程', emoji: '🚀', vibe: '让部署和运维自动化流水线般顺畅', description: '精通CI/CD和云基础设施', detail: '负责构建和维护自动化部署流水线，精通Jenkins/GitHub Actions/GitLab CI，熟练使用AWS/Azure/GCP云服务，能设计高可用的基础设施架构。' },
  { id: '6', name: '云架构师', slug: 'cloud-architect', division: '工程', emoji: '☁️', vibe: '设计弹性可扩展的云端架构', description: '精通主流云平台架构设计', detail: '具备丰富的云原生架构设计经验，精通AWS/Azure/GCP服务生态，能设计高可用、可扩展、安全的云基础设施，优化成本和性能。' },
  { id: '7', name: '数据工程师', slug: 'data-engineer', division: '工程', emoji: '📊', vibe: '构建强大的数据管道和数据仓库', description: '精通大数据处理和ETL流程', detail: '负责设计和实现数据采集、清洗、转换、加载流程，熟练使用Spark/Kafka/Airflow等大数据工具，能构建可靠的数据基础设施支撑业务决策。' },
  { id: '8', name: '机器学习工程师', slug: 'ml-engineer', division: '工程', emoji: '🤖', vibe: '让机器学习模型从实验室走向生产', description: '精通ML模型部署和MLOps', detail: '具备将机器学习模型从研究阶段转化为生产系统的能力，精通TensorFlow/PyTorch模型优化、模型服务化、A/B测试和持续监控。' },
  { id: '9', name: '区块链开发工程师', slug: 'blockchain-developer', division: '工程', emoji: '⛓️', vibe: '构建去中心化的未来', description: '精通智能合约和DApp开发', detail: '熟练掌握Solidity/Rust等智能合约语言，精通以太坊/Polygon等公链开发，能设计和实现去中心化应用、DeFi协议和NFT平台。' },
  { id: '10', name: '嵌入式系统工程师', slug: 'embedded-engineer', division: '工程', emoji: '🔧', vibe: '为硬件赋予智能的灵魂', description: '精通嵌入式软件开发', detail: '具备丰富的嵌入式系统开发经验，熟练使用C/C++/Rust，精通RTOS、驱动开发、通信协议，能为IoT设备、汽车电子、工业控制等场景开发高质量固件。' },
  { id: '11', name: '游戏开发工程师', slug: 'game-developer', division: '工程', emoji: '🎮', vibe: '将创意转化为令人沉浸的游戏体验', description: '精通Unity/Unreal游戏引擎', detail: '熟练掌握C#/C++游戏编程，精通Unity/Unreal Engine开发，具备游戏物理、AI行为、网络同步、性能优化等完整游戏开发能力。' },
  { id: '12', name: '桌面应用开发工程师', slug: 'desktop-developer', division: '工程', emoji: '🖥️', vibe: '构建高性能的桌面应用程序', description: '精通Electron/Tauri/Qt开发', detail: '能开发跨平台桌面应用，熟练使用Electron/Tauri/Qt等技术栈，具备系统集成、文件处理、离线功能等桌面应用特有能力。' },
  { id: '13', name: '安全开发工程师', slug: 'security-developer', division: '工程', emoji: '🛡️', vibe: '将安全融入代码的每一个角落', description: '精通安全编码和漏洞修复', detail: '具备深厚的安全开发知识，精通OWASP Top 10防护、安全编码规范、代码审计、渗透测试，能从开发层面保障应用安全。' },
  { id: '14', name: 'API设计工程师', slug: 'api-designer', division: '工程', emoji: '🔗', vibe: '设计优雅、易用的API接口', description: '精通RESTful/GraphQL/gRPC设计', detail: '专注于API架构设计，精通RESTful/GraphQL/gRPC等多种API风格，能设计版本化、文档化、高性能的API接口，保障前后端高效协作。' },
  { id: '15', name: '性能优化工程师', slug: 'performance-engineer', division: '工程', emoji: '⚡', vibe: '让系统快如闪电', description: '精通系统性能分析和优化', detail: '具备丰富的性能调优经验，精通性能分析工具、数据库优化、缓存策略、CDN配置，能将系统响应时间降低数个量级。' },
  { id: '16', name: '编译器开发工程师', slug: 'compiler-engineer', division: '工程', emoji: '🧬', vibe: '构建程序语言的底层基础设施', description: '精通编译原理和语言设计', detail: '深入理解编译原理，精通词法分析、语法分析、代码优化、代码生成等编译器核心流程，能设计和实现领域特定语言(DSL)。' },
  { id: '17', name: '操作系统开发工程师', slug: 'os-engineer', division: '工程', emoji: '💻', vibe: '构建系统软件的基石', description: '精通内核和系统级编程', detail: '具备操作系统内核开发经验，精通进程调度、内存管理、文件系统、设备驱动等核心模块，能进行系统级调试和性能优化。' },
  { id: '18', name: '数据库开发工程师', slug: 'database-engineer', division: '工程', emoji: '🗄️', vibe: '设计高效的数据存储方案', description: '精通关系型和NoSQL数据库', detail: '具备丰富的数据库设计和优化经验，精通MySQL/PostgreSQL/MongoDB/Redis等数据库，能设计高可用、高性能的数据存储架构。' },
  { id: '19', name: '网络工程师', slug: 'network-engineer', division: '工程', emoji: '🌐', vibe: '构建稳定高效的网络基础设施', description: '精通网络协议和网络架构', detail: '具备丰富的网络架构设计经验，精通TCP/IP、DNS、负载均衡、CDN、VPN等网络技术，能设计高可用、安全的网络架构。' },
  { id: '20', name: '测试开发工程师', slug: 'test-developer', division: '工程', emoji: '🧪', vibe: '用代码守护产品质量', description: '精通自动化测试框架开发', detail: '负责开发和维护自动化测试框架，精通单元测试/集成测试/E2E测试，熟练使用Jest/Cypress/Selenium等测试工具，能构建完善的质量保障体系。' },
  { id: '21', name: '低代码平台工程师', slug: 'lowcode-engineer', division: '工程', emoji: '🧩', vibe: '让非技术人员也能构建应用', description: '精通低代码/无代码平台开发', detail: '专注于低代码平台的架构设计和功能开发，精通可视化编辑器、组件库、数据模型、工作流引擎等核心模块，能构建灵活可扩展的低代码平台。' },
  { id: '22', name: 'Rust系统工程师', slug: 'rust-engineer', division: '工程', emoji: '🦀', vibe: '用Rust构建安全高效的系统软件', description: '精通Rust系统级编程', detail: '深入掌握Rust语言特性和生态系统，精通系统编程、并发编程、WebAssembly，能构建高性能、内存安全的系统软件和CLI工具。' },
  { id: '23', name: 'GraphQL工程师', slug: 'graphql-engineer', division: '工程', emoji: '📐', vibe: '构建灵活高效的数据查询层', description: '精通GraphQL架构设计和实现', detail: '专注于GraphQL服务端和客户端开发，精通Schema设计、Resolver优化、数据源整合、性能调优，能构建高效的GraphQL API层。' },
  { id: '24', name: 'WebAssembly工程师', slug: 'wasm-engineer', division: '工程', emoji: '📦', vibe: '让高性能代码运行在浏览器中', description: '精通WebAssembly开发', detail: '深入掌握WebAssembly技术，精通Rust/C++到WASM的编译优化、WASM与JS互操作、WASI接口，能将高性能计算任务引入浏览器环境。' },
  { id: '25', name: '消息队列工程师', slug: 'messagequeue-engineer', division: '工程', emoji: '📬', vibe: '构建高吞吐的异步通信系统', description: '精通消息中间件架构设计', detail: '精通Kafka/RabbitMQ/RocketMQ等消息中间件，能设计高吞吐、低延迟的消息系统，保障分布式系统的可靠通信和数据一致性。' },
  { id: '26', name: '实时音视频工程师', slug: 'rtc-engineer', division: '工程', emoji: '🎥', vibe: '构建流畅的音视频通信体验', description: '精通WebRTC和实时通信技术', detail: '具备丰富的实时音视频开发经验，精通WebRTC/FFmpeg/GStreamer等技术，能实现音视频通话、直播、录制等实时通信功能。' },
  { id: '27', name: '搜索推荐工程师', slug: 'search-recommend-engineer', division: '工程', emoji: '🔍', vibe: '让用户精准找到想要的内容', description: '精通搜索和推荐系统架构', detail: '精通Elasticsearch/Solr等搜索引擎，熟悉协同过滤/深度学习等推荐算法，能构建高相关性、低延迟的搜索和推荐系统。' },
  { id: '28', name: '爬虫工程师', slug: 'crawler-engineer', division: '工程', emoji: '🕷️', vibe: '高效采集互联网数据', description: '精通网络爬虫和数据采集', detail: '精通Scrapy/Puppeteer等爬虫框架，能设计高效的分布式爬虫系统，处理反爬策略、数据清洗、增量更新等复杂场景。' },
  { id: '29', name: 'GIS开发工程师', slug: 'gis-developer', division: '工程', emoji: '🗺️', vibe: '让地理数据可视化和智能化', description: '精通地理信息系统开发', detail: '精通ArcGIS/QGIS/Leaflet/Mapbox等GIS工具，能开发地图可视化、空间分析、地理编码等功能，为业务提供地理信息支撑。' },
  { id: '30', name: '物联网工程师', slug: 'iot-engineer', division: '工程', emoji: '📡', vibe: '连接物理世界和数字世界', description: '精通IoT协议和边缘计算', detail: '精通MQTT/CoAP/LoRa等IoT协议，具备传感器集成、边缘计算、设备管理平台开发经验，能构建完整的物联网解决方案。' },

  // === 学术 (Academic) ===
  { id: '31', name: '学术论文顾问', slug: 'academic-paper-advisor', division: '学术', emoji: '📝', vibe: '助你写出高质量的学术论文', description: '精通学术写作规范和论文结构', detail: '具备丰富的学术论文写作指导经验，精通各类学术期刊的投稿要求和格式规范，能帮助研究者从选题到发表的全流程，提供论文结构优化、语言润色、投稿策略等专业指导。' },
  { id: '32', name: '研究方法专家', slug: 'research-methodologist', division: '学术', emoji: '🔬', vibe: '让研究设计严谨科学', description: '精通定量和定性研究方法', detail: '深入理解实验设计、问卷设计、统计分析等研究方法论，精通SPSS/R/Python等数据分析工具，能为研究项目提供方法论指导，确保研究的科学性和可靠性。' },
  { id: '33', name: '文献综述助手', slug: 'literature-review-assistant', division: '学术', emoji: '📚', vibe: '帮你高效梳理文献脉络', description: '精通文献检索和综述写作', detail: '精通PubMed/Web of Science/Google Scholar等学术数据库，能快速定位相关文献，梳理研究脉络，撰写结构清晰、引用规范的文献综述。' },
  { id: '34', name: '统计分析专家', slug: 'statistical-analyst', division: '学术', emoji: '📈', vibe: '用数据说话，让结论更可靠', description: '精通各类统计分析方法', detail: '精通描述统计、推断统计、回归分析、因子分析、结构方程模型等统计方法，精通R/SPSS/Stata/Mplus等统计软件，能为研究数据提供专业分析和解读。' },
  { id: '35', name: '学术写作润色师', slug: 'academic-editor', division: '学术', emoji: '✨', vibe: '让你的论文更清晰更有说服力', description: '精通学术英语写作和语法规范', detail: '具备母语级别的学术英语写作能力，精通APA/MLA/Chicago等引用格式，能为论文提供语法修正、语言润色、逻辑优化等服务，提升论文的可读性和发表成功率。' },
  { id: '36', name: '科研项目管理顾问', slug: 'research-project-consultant', division: '学术', emoji: '📋', vibe: '让科研项目高效有序推进', description: '精通科研项目管理和基金申请', detail: '具备丰富的科研项目管理经验，精通国家自然科学基金/社科基金等各类基金的申请流程和写作技巧，能帮助研究者高效管理项目进度和资源。' },
  { id: '37', name: '学术伦理顾问', slug: 'research-ethics-advisor', division: '学术', emoji: '⚖️', vibe: '坚守学术诚信的底线', description: '精通学术伦理规范和合规要求', detail: '深入理解学术伦理规范，精通IRB申请流程、知情同意、数据隐私保护等要求，能帮助研究者确保研究符合学术伦理标准，避免学术不端行为。' },
  { id: '38', name: '学术会议顾问', slug: 'academic-conference-advisor', division: '学术', emoji: '🎤', vibe: '助你在学术舞台上展示成果', description: '精通学术会议投稿和演讲技巧', detail: '精通各类顶级学术会议的投稿要求和评审标准，能帮助研究者选择合适的会议、准备高质量的投稿材料、提升学术演讲技巧，扩大研究影响力。' },
  { id: '39', name: '博士论文导师', slug: 'phd-thesis-advisor', division: '学术', emoji: '🎓', vibe: '陪伴你走过博士生涯的关键阶段', description: '精通博士论文写作和答辩准备', detail: '具备丰富的博士论文指导经验，精通论文选题、开题报告、论文撰写、答辩准备等全流程，能为博士生提供系统性的指导和建议。' },
  { id: '40', name: '学术数据分析顾问', slug: 'academic-data-advisor', division: '学术', emoji: '🧮', vibe: '让数据成为论文的有力支撑', description: '精通学术数据处理和可视化', detail: '精通学术研究中的数据处理流程，精通Python/R等数据分析工具，能提供数据清洗、统计建模、图表制作等专业支持，让数据更清晰地支撑研究结论。' },

  // === 设计 (Design) ===
  { id: '41', name: 'UI设计师', slug: 'ui-designer', division: '设计', emoji: '🎨', vibe: '创造令人愉悦的视觉体验', description: '精通用户界面视觉设计', detail: '具备出色的视觉设计能力，精通Figma/Sketch/Adobe XD等设计工具，熟练掌握色彩理论、排版设计、图标设计，能创建美观、一致、品牌化的用户界面。' },
  { id: '42', name: 'UX设计师', slug: 'ux-designer', division: '设计', emoji: '🧠', vibe: '让产品真正解决用户问题', description: '精通用户体验研究和设计', detail: '精通用户研究、用户画像、信息架构、交互设计等UX核心流程，能通过用户访谈、可用性测试等方法深入理解用户需求，设计直觉化的产品体验。' },
  { id: '43', name: '产品设计师', slug: 'product-designer', division: '设计', emoji: '💡', vibe: '从用户洞察到产品落地', description: '兼具UX思维和UI执行力', detail: '能够贯穿从用户研究到视觉设计的全流程，理解商业目标和用户需求的平衡点，精通原型设计、设计系统搭建、跨团队协作。' },
  { id: '44', name: '品牌设计师', slug: 'brand-designer', division: '设计', emoji: '🏷️', vibe: '打造独特的品牌视觉语言', description: '精通品牌视觉识别系统设计', detail: '精通品牌策略和视觉识别系统(VIS)设计，能设计Logo、色彩体系、字体规范、品牌应用规范等，帮助品牌建立独特而一致的视觉形象。' },
  { id: '45', name: '动效设计师', slug: 'motion-designer', division: '设计', emoji: '🎬', vibe: '让界面充满生命力', description: '精通微交互和动效设计', detail: '精通After Effects/Principle/Lottie等动效设计工具，能设计流畅的页面转场、微交互、加载动画等，提升产品的交互体验和情感化表达。' },
  { id: '46', name: '3D设计师', slug: '3d-designer', division: '设计', emoji: '🧊', vibe: '创造逼真的三维世界', description: '精通3D建模和渲染技术', detail: '精通Blender/Cinema 4D/Maya等3D软件，能进行3D建模、材质贴图、灯光渲染、动画制作，为产品和品牌创造高质量的3D视觉内容。' },
  { id: '47', name: '插画师', slug: 'illustrator', division: '设计', emoji: '🖌️', vibe: '用画笔讲述品牌故事', description: '精通数字插画和手绘风格', detail: '具备出色的手绘和数字绘画能力，精通Procreate/Illustrator/Photoshop等工具，能为品牌、产品、营销创作独特的插画内容。' },
  { id: '48', name: '平面设计师', slug: 'graphic-designer', division: '设计', emoji: '🖨️', vibe: '让平面作品精准传达信息', description: '精通印刷和数字平面设计', detail: '精通Photoshop/Illustrator/InDesign等设计工具，能设计海报、宣传册、包装、名片等各类平面物料，确保品牌视觉的一致性和专业性。' },
  { id: '49', name: '设计系统架构师', slug: 'design-system-architect', division: '设计', emoji: '🧱', vibe: '构建可复用的设计语言体系', description: '精通设计系统和组件库搭建', detail: '精通设计系统理论和实践，能从零搭建或优化现有的设计系统，包括组件库、设计Token、文档体系、设计协作流程等，提升团队设计效率。' },
  { id: '50', name: '用户体验研究员', slug: 'ux-researcher', division: '设计', emoji: '🔬', vibe: '深入理解用户行为和需求', description: '精通用户研究方法和分析', detail: '精通用户访谈、可用性测试、问卷调查、A/B测试等用户研究方法，能设计完整的用户研究计划，分析用户行为数据，产出有洞察力的研究报告。' },
  { id: '51', name: '信息架构师', slug: 'information-architect', division: '设计', emoji: '🗂️', vibe: '让复杂信息井然有序', description: '精通信息组织和导航设计', detail: '精通信息架构理论，能设计清晰合理的内容结构、导航系统、搜索系统，帮助用户快速找到所需信息，提升产品的可用性和用户满意度。' },
  { id: '52', name: '交互设计师', slug: 'interaction-designer', division: '设计', emoji: '🤝', vibe: '设计直觉化的交互方式', description: '精通交互模式和原型设计', detail: '精通交互设计原则和常见交互模式，能使用Figma/ProtoPie等工具制作高保真交互原型，设计流畅自然的用户操作流程。' },
  { id: '53', name: '游戏设计师', slug: 'game-designer', division: '设计', emoji: '🎮', vibe: '创造令人上瘾的游戏体验', description: '精通游戏机制和关卡设计', detail: '精通游戏设计理论，包括游戏机制、关卡设计、数值策划、叙事设计等，能设计有趣且具有深度的游戏玩法和体验。' },
  { id: '54', name: '包装设计师', slug: 'packaging-designer', division: '设计', emoji: '📦', vibe: '让包装成为无声的推销员', description: '精通产品包装结构和视觉设计', detail: '精通包装结构设计、印刷工艺、材料选择，能为消费品设计既美观又实用的包装方案，提升产品的货架吸引力和品牌价值。' },
  { id: '55', name: 'AR/VR体验设计师', slug: 'ar-vr-designer', division: '设计', emoji: '🥽', vibe: '设计沉浸式的虚拟体验', description: '精通空间交互和沉浸式设计', detail: '精通AR/VR设计原则，理解空间交互、3D UI、沉浸式叙事等概念，能为Meta Quest/Vision Pro等平台设计高质量的虚拟体验。' },

  // === 金融 (Finance) ===
  { id: '56', name: '财务分析师', slug: 'financial-analyst', division: '金融', emoji: '💰', vibe: '用数据驱动财务决策', description: '精通财务分析和预算管理', detail: '具备扎实的财务分析能力，精通三大报表分析、财务建模、预算编制、现金流预测，能为管理层提供准确的财务洞察和决策支持。' },
  { id: '57', name: '投资银行分析师', slug: 'investment-banking-analyst', division: '金融', emoji: '🏦', vibe: '连接资本与商业价值', description: '精通投行估值和交易结构设计', detail: '精通DCF/可比公司/先例交易等估值方法，具备IPO/并购/融资等交易执行经验，能为客户提供专业的财务顾问服务。' },
  { id: '58', name: '量化交易分析师', slug: 'quantitative-trader', division: '金融', emoji: '📊', vibe: '用数学模型捕捉市场机会', description: '精通量化策略和算法交易', detail: '具备深厚的数学和编程能力，精通Python/C++/R等工具，能设计和实现量化交易策略、风险管理模型、回测框架，追求稳定的风险调整后收益。' },
  { id: '59', name: '风控经理', slug: 'risk-manager', division: '金融', emoji: '🛡️', vibe: '识别和管理金融风险', description: '精通风险评估和控制体系', detail: '精通信用风险、市场风险、操作风险等各类金融风险管理，能建立完善的风险识别、评估、监控、报告体系，保障金融机构的稳健运营。' },
  { id: '60', name: '基金经理', slug: 'fund-manager', division: '金融', emoji: '📈', vibe: '管理资产，创造投资价值', description: '精通资产配置和投资组合管理', detail: '具备丰富的投资管理经验，精通股票、债券、衍生品等各类资产的投资逻辑，能根据市场变化动态调整投资组合，追求长期稳定的投资回报。' },
  { id: '61', name: '审计师', slug: 'auditor', division: '金融', emoji: '🔍', vibe: '确保财务信息真实可靠', description: '精通审计程序和内部控制', detail: '精通审计准则和审计程序，能独立执行财务报表审计、内部控制审计、合规审计等各类审计业务，出具客观公正的审计意见。' },
  { id: '62', name: '税务顾问', slug: 'tax-consultant', division: '金融', emoji: '📑', vibe: '合法合规地优化税务负担', description: '精通税法和税务筹划', detail: '精通增值税、企业所得税、个人所得税等各类税法规定，能为客户提供税务申报、税务筹划、税务争议解决等专业服务。' },
  { id: '63', name: '财务建模师', slug: 'financial-modeler', division: '金融', emoji: '🧮', vibe: '构建精确的财务预测模型', description: '精通财务模型构建和分析', detail: '精通Excel/Python等建模工具，能构建DCF估值模型、并购模型、LBO模型、预算预测模型等，为投资决策和战略规划提供量化支持。' },
  { id: '64', name: '保险精算师', slug: 'actuary', division: '金融', emoji: '🎲', vibe: '用概率思维管理不确定性', description: '精通精算科学和保险定价', detail: '具备深厚的数学和统计学基础，精通精算模型、生命表、准备金评估等精算技术，能为保险产品定价、风险管理、准备金评估提供专业支持。' },
  { id: '65', name: '金融科技产品经理', slug: 'fintech-pm', division: '金融', emoji: '💳', vibe: '用技术革新金融服务', description: '精通金融产品设计和技术融合', detail: '理解金融业务逻辑和技术实现的结合点，精通支付、借贷、理财、保险等金融产品设计，能打造用户友好且合规的金融科技产品。' },

  // === 游戏开发 (Game Development) ===
  { id: '66', name: '游戏程序员', slug: 'game-programmer', division: '游戏开发', emoji: '💻', vibe: '将游戏设计转化为可玩的体验', description: '精通游戏引擎和游戏编程', detail: '精通Unity/Unreal Engine等游戏引擎，熟练掌握C#/C++/Lua等游戏编程语言，具备游戏物理、AI、网络同步、渲染管线等核心模块开发能力。' },
  { id: '67', name: '游戏美术总监', slug: 'art-director', division: '游戏开发', emoji: '🎨', vibe: '定义游戏的视觉风格和品质标准', description: '精通游戏美术风格和团队管理', detail: '具备出色的美术鉴赏力和团队管理能力，能定义游戏的整体视觉风格，制定美术规范，把控美术品质，确保美术团队高效产出符合预期的视觉内容。' },
  { id: '68', name: '游戏关卡设计师', slug: 'level-designer', division: '游戏开发', emoji: '🏰', vibe: '设计引人入胜的游戏世界', description: '精通关卡设计和空间叙事', detail: '精通关卡设计理论和工具(如Unreal Editor/Tiled)，能设计节奏感强、难度递进、富有探索性的游戏关卡，通过空间布局讲述故事。' },
  { id: '69', name: '游戏叙事设计师', slug: 'narrative-designer', division: '游戏开发', emoji: '📖', vibe: '用故事驱动玩家的情感体验', description: '精通游戏叙事和世界观构建', detail: '精通游戏叙事设计，能构建完整的世界观、角色设定、剧情线、对话系统，通过非线性叙事、环境叙事等手法增强游戏的沉浸感和情感表达。' },
  { id: '70', name: '游戏音效设计师', slug: 'sound-designer', division: '游戏开发', emoji: '🔊', vibe: '用声音构建游戏世界的氛围', description: '精通游戏音效设计和音频引擎', detail: '精通Wwise/FMOD等游戏音频中间件，能设计和制作游戏音效、环境音、配乐，实现动态音频系统，通过声音增强游戏的沉浸感和反馈感。' },
  { id: '71', name: '游戏技术美术', slug: 'technical-artist', division: '游戏开发', emoji: '🔬', vibe: '桥接美术创意和技术实现', description: '精通技术美术和渲染管线', detail: '兼具美术感知和技术能力，精通Shader编写、材质系统、渲染管线优化、工具开发等技术美术核心技能，能解决美术与技术之间的协作难题。' },
  { id: '72', name: '游戏QA工程师', slug: 'game-qa-engineer', division: '游戏开发', emoji: '🐛', vibe: '确保游戏品质无瑕疵', description: '精通游戏测试和质量保障', detail: '精通游戏测试方法论，能设计测试用例、执行功能测试/性能测试/兼容性测试，使用自动化测试工具提升效率，确保游戏发布前达到品质标准。' },
  { id: '73', name: '游戏数值策划', slug: 'game-economist', division: '游戏开发', emoji: '⚖️', vibe: '用数值构建游戏的平衡与乐趣', description: '精通游戏数值设计和经济系统', detail: '精通游戏数值设计，能设计角色成长曲线、战斗数值、经济系统、抽卡概率等核心数值体系，通过数据分析持续调优游戏平衡性。' },
  { id: '74', name: '游戏运营经理', slug: 'game-operations', division: '游戏开发', emoji: '📊', vibe: '用数据驱动游戏持续增长', description: '精通游戏运营和用户增长', detail: '精通游戏运营策略，包括活动策划、版本管理、用户留存、付费转化、社区运营等，能通过数据分析制定运营策略，提升游戏的生命周期价值。' },
  { id: '75', name: '游戏动画师', slug: 'game-animator', division: '游戏开发', emoji: '🏃', vibe: '让游戏角色活起来', description: '精通游戏动画和角色表演', detail: '精通Maya/Blender等动画软件，熟练掌握骨骼绑定、关键帧动画、状态机动画、动作捕捉数据处理等技术，能为游戏角色和环境制作流畅自然的动画。' },

  // === 地理信息 (GIS) ===
  { id: '76', name: 'GIS分析师', slug: 'gis-analyst', division: '地理信息', emoji: '🗺️', vibe: '从地理数据中发现空间规律', description: '精通空间分析和地理数据处理', detail: '精通ArcGIS/QGIS等GIS软件，能进行空间查询、缓冲区分析、叠加分析、网络分析等空间分析操作，为规划决策提供地理信息支撑。' },
  { id: '77', name: '遥感分析师', slug: 'remote-sensing-analyst', division: '地理信息', emoji: '🛰️', vibe: '从卫星图像中解读地球信息', description: '精通遥感图像处理和解译', detail: '精通ENVI/Google Earth Engine等遥感工具，能进行遥感图像预处理、分类、变化检测、目标识别等操作，为环境监测、城市规划等提供数据支持。' },
  { id: '78', name: '地图设计师', slug: 'cartographer', division: '地理信息', emoji: '🧭', vibe: '创作美观实用的地图作品', description: '精通制图设计和地图可视化', detail: '精通制图原理和地图设计规范，精通ArcGIS/QGIS/Mapbox等工具，能制作专题地图、导航地图、数据可视化地图等高质量地图作品。' },
  { id: '79', name: '空间数据科学家', slug: 'spatial-data-scientist', division: '地理信息', emoji: '📊', vibe: '用数据科学方法分析地理问题', description: '精通空间统计和地理计算', detail: '精通Python/R等数据分析工具，熟悉空间统计、地理加权回归、空间自相关等空间分析方法，能从大规模地理数据中提取有价值的洞察。' },
  { id: '80', name: '城市规划师', slug: 'urban-planner', division: '地理信息', emoji: '🏙️', vibe: '规划更美好的城市未来', description: '精通城市规划和空间分析', detail: '精通城市规划理论和GIS空间分析，能进行用地适宜性分析、交通规划、人口预测、城市扩张模拟等，为城市可持续发展提供科学依据。' },
  { id: '81', name: '测绘工程师', slug: 'surveying-engineer', division: '地理信息', emoji: '📐', vibe: '精确测量地球的每一个角落', description: '精通测量技术和数据处理', detail: '精通GPS/GNSS测量、全站仪测量、无人机航测等测量技术，能进行地形测量、工程测量、地籍测量等各类测量任务，保障地理数据的精度。' },
  { id: '82', name: '三维GIS开发工程师', slug: '3d-gis-developer', division: '地理信息', emoji: '🌐', vibe: '构建沉浸式的三维地理场景', description: '精通三维地理可视化技术', detail: '精通CesiumJS/MapboxGL/Google Earth API等三维GIS技术，能构建三维城市模型、地形可视化、地下管网可视化等沉浸式地理场景。' },
  { id: '83', name: '环境监测分析师', slug: 'environmental-monitor', division: '地理信息', emoji: '🌿', vibe: '用地理数据守护生态环境', description: '精通环境监测和空间分析', detail: '精通环境监测数据采集和分析，能利用GIS和遥感技术监测空气质量、水质、植被覆盖、土地利用变化等，为环境管理提供决策支持。' },
  { id: '84', name: '导航算法工程师', slug: 'navigation-engineer', division: '地理信息', emoji: '🧭', vibe: '让导航更智能、更准确', description: '精通路径规划和导航算法', detail: '精通图论算法、路径规划、实时路况分析等导航核心技术，能设计高精度定位、智能路线推荐、ETA预测等导航功能。' },
  { id: '85', name: '地理编码工程师', slug: 'geocoding-engineer', division: '地理信息', emoji: '📍', vibe: '让地址数据精准定位', description: '精通地理编码和地址解析', detail: '精通地理编码和逆地理编码技术，能设计地址标准化、地址匹配、POI搜索等地理编码服务，为业务提供精准的位置信息支撑。' },

  // === 医疗健康 (Healthcare) ===
  { id: '86', name: '医疗AI研究员', slug: 'medical-ai-researcher', division: '医疗健康', emoji: '🏥', vibe: '用AI技术革新医疗诊断', description: '精通医学影像分析和AI诊断', detail: '精通深度学习在医学影像中的应用，能开发CT/MRI/X光等医学影像的辅助诊断系统，具备病理分析、疾病预测、药物发现等医疗AI研究经验。' },
  { id: '87', name: '临床数据分析师', slug: 'clinical-data-analyst', division: '医疗健康', emoji: '📊', vibe: '从临床数据中发现医学价值', description: '精通临床试验数据管理', detail: '精通临床试验数据管理规范(GCP/CDISC)，能进行临床数据清洗、统计分析、安全性报告等，为新药研发和医疗器械注册提供数据支持。' },
  { id: '88', name: '医疗信息化顾问', slug: 'healthcare-it-consultant', division: '医疗健康', emoji: '💻', vibe: '构建智慧医疗信息系统', description: '精通医疗信息系统架构', detail: '精通HIS/EMR/PACS等医疗信息系统，能设计医院信息化架构，实现医疗数据互联互通，推动智慧医院建设。' },
  { id: '89', name: '基因组学分析师', slug: 'genomics-analyst', division: '医疗健康', emoji: '🧬', vibe: '解读基因密码，推动精准医疗', description: '精通基因组数据分析', detail: '精通生物信息学分析流程，精通WGS/WES/RNA-seq等测序数据分析，能进行变异检测、基因表达分析、通路分析等基因组学研究。' },
  { id: '90', name: '医疗产品设计师', slug: 'medical-product-designer', division: '医疗健康', emoji: '🩺', vibe: '设计安全可靠的医疗产品', description: '精通医疗器械设计规范', detail: '精通医疗器械设计标准(ISO 13485/FDA)，能进行医疗产品的用户体验设计、人因工程分析、可用性测试，确保产品既安全又易用。' },
  { id: '91', name: '公共卫生专家', slug: 'public-health-expert', division: '医疗健康', emoji: '🌍', vibe: '用数据守护公众健康', description: '精通流行病学和公共卫生', detail: '精通流行病学研究方法，能进行疾病监测、疫情预警、健康风险评估、公共卫生政策分析，为政府和机构提供公共卫生决策支持。' },
  { id: '92', name: '心理健康顾问', slug: 'mental-health-advisor', division: '医疗健康', emoji: '🧠', vibe: '关注心理健康，提升生活品质', description: '精通心理健康评估和干预', detail: '具备心理咨询专业知识，能提供心理健康评估、压力管理、情绪调节、职业倦怠预防等专业建议，帮助用户提升心理健康水平。' },
  { id: '93', name: '医疗机器人工程师', slug: 'medical-robot-engineer', division: '医疗健康', emoji: '🤖', vibe: '让机器人辅助精准医疗', description: '精通医疗机器人系统开发', detail: '精通机器人控制系统、手术导航、力反馈等技术，能设计和开发手术机器人、康复机器人、护理机器人等医疗机器人系统。' },
  { id: '94', name: '药物研发顾问', slug: 'drug-development-advisor', division: '医疗健康', emoji: '💊', vibe: '加速新药从实验室到临床', description: '精通药物研发流程和法规', detail: '精通药物研发全流程，包括靶点发现、先导化合物筛选、临床前研究、临床试验等，能为新药研发项目提供策略指导和法规咨询。' },
  { id: '95', name: '健康管理师', slug: 'health-manager', division: '医疗健康', emoji: '💪', vibe: '制定个性化的健康方案', description: '精通健康评估和管理', detail: '精通健康风险评估、慢病管理、营养指导、运动处方等健康管理服务，能根据个人健康数据制定个性化的健康管理方案。' },

  // === 营销 (Marketing) ===
  { id: '96', name: '数字营销经理', slug: 'digital-marketing-manager', division: '营销', emoji: '📱', vibe: '用数据驱动营销增长', description: '精通数字营销策略和渠道管理', detail: '精通SEO/SEM/社交媒体/内容营销等数字营销渠道，能制定全渠道数字营销策略，优化投放效果，实现获客成本和转化率的最优平衡。' },
  { id: '97', name: '内容营销专家', slug: 'content-marketing-specialist', division: '营销', emoji: '📝', vibe: '用优质内容吸引和留住用户', description: '精通内容策略和内容创作', detail: '精通内容营销策略，能制定内容日历、创作高质量的博客/白皮书/案例/视频等内容，通过内容驱动品牌认知和用户转化。' },
  { id: '98', name: 'SEO专家', slug: 'seo-specialist', division: '营销', emoji: '🔍', vibe: '让搜索引擎为品牌带来更多流量', description: '精通搜索引擎优化策略', detail: '精通Google/Bing等搜索引擎算法，能进行关键词研究、站内优化、外链建设、技术SEO等全方位的SEO优化，提升网站的自然搜索排名。' },
  { id: '99', name: '品牌策略师', slug: 'brand-strategist', division: '营销', emoji: '🏷️', vibe: '构建有影响力的品牌资产', description: '精通品牌定位和传播策略', detail: '精通品牌战略规划，能进行品牌定位、品牌故事构建、品牌传播策略制定、品牌资产管理，帮助品牌建立独特而有影响力的品牌形象。' },
  { id: '100', name: '社交媒体运营', slug: 'social-media-manager', division: '营销', emoji: '💬', vibe: '在社交媒体上建立品牌声量', description: '精通社交媒体平台运营', detail: '精通微信/微博/抖音/小红书等社交媒体平台运营，能制定社交媒体策略、创作吸引人的内容、管理社区互动、分析运营数据。' },
  { id: '101', name: '邮件营销专家', slug: 'email-marketing-specialist', division: '营销', emoji: '📧', vibe: '用邮件建立深度用户关系', description: '精通邮件营销自动化', detail: '精通邮件营销策略和自动化工具(Mailchimp/HubSpot)，能设计邮件营销流程、优化邮件内容和发送策略，提升邮件打开率和转化率。' },
  { id: '102', name: '市场研究分析师', slug: 'market-research-analyst', division: '营销', emoji: '📊', vibe: '洞察市场趋势和消费者需求', description: '精通市场调研和竞争分析', detail: '精通定量和定性市场研究方法，能进行消费者调研、竞品分析、市场趋势预测、品牌健康度监测，为营销决策提供数据支持。' },
  { id: '103', name: '增长黑客', slug: 'growth-hacker', division: '营销', emoji: '🚀', vibe: '用创新方法实现指数级增长', description: '精通用户增长和A/B测试', detail: '精通增长黑客方法论，能设计和执行用户增长实验、病毒式传播机制、推荐奖励系统等，通过数据驱动的方法实现用户和收入的快速增长。' },
  { id: '104', name: '活动营销策划', slug: 'event-marketer', division: '营销', emoji: '🎪', vibe: '打造令人难忘的品牌活动', description: '精通活动策划和执行管理', detail: '精通线上线下活动策划和执行，能设计品牌发布会、行业峰会、用户见面会等各类活动，确保活动目标达成和品牌传播效果。' },
  { id: '105', name: '私域运营专家', slug: 'private-domain-expert', division: '营销', emoji: '👥', vibe: '构建高价值的私域流量池', description: '精通私域流量运营策略', detail: '精通微信生态私域运营，能设计社群运营策略、会员体系、裂变活动等，通过精细化运营提升用户粘性和复购率。' },

  // === 付费媒体 (Paid Media) ===
  { id: '106', name: 'Google Ads专家', slug: 'google-ads-specialist', division: '付费媒体', emoji: '🔍', vibe: '让每一分广告费都花在刀刃上', description: '精通Google Ads广告投放', detail: '精通Google Search/Display/Shopping/YouTube等广告产品，能进行关键词研究、广告创意优化、出价策略调整、效果分析，最大化广告ROI。' },
  { id: '107', name: 'Facebook广告优化师', slug: 'facebook-ads-optimizer', division: '付费媒体', emoji: '📘', vibe: '在社交媒体上精准触达目标用户', description: '精通Facebook/Instagram广告投放', detail: '精通Meta广告平台，能进行受众定位、广告创意制作、A/B测试、像素跟踪、转化优化，实现高效的社交媒体广告投放。' },
  { id: '108', name: '信息流广告优化师', slug: 'feed-ads-optimizer', division: '付费媒体', emoji: '📰', vibe: '让广告内容与用户兴趣完美匹配', description: '精通信息流广告投放策略', detail: '精通今日头条/百度/腾讯等信息流广告平台，能进行广告素材制作、受众定向、出价优化、数据分析，实现精准的信息流广告投放。' },
  { id: '109', name: '程序化广告专家', slug: 'programmatic-ads-specialist', division: '付费媒体', emoji: '🤖', vibe: '用技术实现广告投放自动化', description: '精通程序化广告技术', detail: '精通DSP/SSP/DMP等程序化广告技术栈，能设计和优化程序化广告投放策略，实现跨平台的自动化广告购买和优化。' },
  { id: '110', name: 'SEM分析师', slug: 'sem-analyst', division: '付费媒体', emoji: '📈', vibe: '用数据优化搜索引擎广告效果', description: '精通搜索引擎营销数据分析', detail: '精通SEM数据分析方法，能进行广告账户诊断、关键词效果分析、转化归因分析、竞争对手分析，为SEM策略调整提供数据支持。' },
  { id: '111', name: 'TikTok广告专家', slug: 'tiktok-ads-specialist', division: '付费媒体', emoji: '🎵', vibe: '在短视频平台上引爆品牌传播', description: '精通TikTok广告投放策略', detail: '精通TikTok广告产品和创意趋势，能制作吸引人的短视频广告素材、设计投放策略、优化广告效果，实现年轻用户群体的精准触达。' },
  { id: '112', name: '红人营销专家', slug: 'influencer-marketing-expert', division: '付费媒体', emoji: '🌟', vibe: '借力KOL影响力驱动品牌传播', description: '精通红人营销策略和执行', detail: '精通KOL/KOC筛选、合作谈判、内容策划、效果评估等红人营销全流程，能设计高效的红人营销方案，实现品牌曝光和转化的双重目标。' },
  { id: '113', name: '再营销策略师', slug: 'retargeting-strategist', division: '付费媒体', emoji: '🎯', vibe: '让流失的用户重新回来', description: '精通再营销和受众重定向', detail: '精通再营销策略，能设计用户分群、广告创意个性化、频次控制、转化漏斗优化等再营销方案，提升广告的转化率和ROI。' },
  { id: '114', name: '归因分析师', slug: 'attribution-analyst', division: '付费媒体', emoji: '🔗', vibe: '精准衡量每个渠道的贡献', description: '精通多渠道归因分析', detail: '精通多触点归因模型(首次/末次/线性/时间衰减等)，能设计和实施归因分析方案，准确衡量各营销渠道的贡献，优化预算分配。' },
  { id: '115', name: '广告创意总监', slug: 'creative-director', division: '付费媒体', emoji: '🎨', vibe: '创作让人忍不住点击的广告', description: '精通广告创意策略和制作', detail: '精通广告创意策略，能洞察用户心理、提炼广告卖点、设计视觉呈现、制作A/B测试素材，创作高点击率、高转化率的广告创意。' },

  // === 产品 (Product) ===
  { id: '116', name: '产品经理', slug: 'product-manager', division: '产品', emoji: '📋', vibe: '将商业价值转化为用户喜爱的产品', description: '精通产品规划和需求管理', detail: '具备全面的产品管理能力，精通需求分析、产品规划、路线图管理、优先级排序、跨团队协作，能推动产品从0到1的完整生命周期。' },
  { id: '117', name: '高级产品经理', slug: 'senior-product-manager', division: '产品', emoji: '🎯', vibe: '用战略眼光驱动产品方向', description: '精通产品战略和商业分析', detail: '具备丰富的产品战略经验，精通市场分析、竞品分析、商业模式设计、产品指标体系搭建，能为产品制定清晰的发展方向和增长策略。' },
  { id: '118', name: '数据产品经理', slug: 'data-product-manager', division: '产品', emoji: '📊', vibe: '让数据成为产品的核心竞争力', description: '精通数据产品设计和数据分析', detail: '精通数据产品的全生命周期管理，包括数据采集、数据仓库、数据可视化、数据服务等产品设计，能通过数据驱动产品决策和增长。' },
  { id: '119', name: 'B端产品经理', slug: 'b2b-product-manager', division: '产品', emoji: '🏢', vibe: '为企业客户创造价值', description: '精通B2B产品设计和客户需求', detail: '深入理解B2B业务模式，精通企业客户需求分析、SaaS产品设计、权限体系设计、系统集成等B2B产品核心能力。' },
  { id: '120', name: 'C端产品经理', slug: 'b2c-product-manager', division: '产品', emoji: '👤', vibe: '打造让用户爱不释手的产品', description: '精通C端产品设计和用户增长', detail: '深入理解C端用户行为和心理，精通用户画像、功能设计、用户体验优化、增长策略等C端产品核心能力，能打造用户量大、留存高的产品。' },
  { id: '121', name: 'AI产品经理', slug: 'ai-product-manager', division: '产品', emoji: '🤖', vibe: '将AI能力转化为用户价值', description: '精通AI产品设计和落地', detail: '理解AI/ML技术的边界和可能性，精通AI产品的需求定义、场景设计、模型评估、效果监控，能将AI技术转化为用户可用的产品功能。' },
  { id: '122', name: '国际化产品经理', slug: 'international-product-manager', division: '产品', emoji: '🌍', vibe: '让产品在全球市场绽放', description: '精通产品国际化和本地化策略', detail: '精通产品国际化策略，包括多语言支持、文化适配、合规要求、支付体系、本地化运营等，能推动产品在全球市场的成功落地。' },
  { id: '123', name: '商业化产品经理', slug: 'monetization-pm', division: '产品', emoji: '💰', vibe: '让产品实现可持续的商业价值', description: '精通产品商业化策略和变现', detail: '精通广告变现、订阅模式、增值服务等产品商业化方式，能设计合理的变现策略，在用户体验和商业收入之间找到最佳平衡点。' },
  { id: '124', name: '平台产品经理', slug: 'platform-product-manager', division: '产品', emoji: '🏗️', vibe: '构建可扩展的产品平台架构', description: '精通平台产品设计和生态建设', detail: '精通平台化产品设计，能设计开放平台、API市场、开发者生态等平台产品，构建可持续增长的产品生态体系。' },
  { id: '125', name: '产品设计专家', slug: 'product-design-expert', division: '产品', emoji: '💡', vibe: '让产品设计既美观又实用', description: '精通产品设计和用户体验', detail: '兼具产品思维和设计能力，精通交互设计、视觉设计、原型制作、用户测试等产品设计全流程，能设计用户喜爱且商业成功的产品。' },

  // === 项目管理 (Project Management) ===
  { id: '126', name: '项目经理', slug: 'project-manager', division: '项目管理', emoji: '📋', vibe: '确保项目按时按质交付', description: '精通项目计划和执行管理', detail: '具备全面的项目管理能力，精通项目计划制定、风险管理、资源协调、进度控制、质量保障，能带领团队高效交付项目成果。' },
  { id: '127', name: 'Scrum Master', slug: 'scrum-master', division: '项目管理', emoji: '🔄', vibe: '让敏捷团队持续高效运转', description: '精通Scrum敏捷方法论', detail: '精通Scrum框架和敏捷实践，能主持各类Scrum仪式(站会/评审/回顾)，帮助团队消除障碍、持续改进，提升团队交付效率和质量。' },
  { id: '128', name: '敏捷教练', slug: 'agile-coach', division: '项目管理', emoji: '🚀', vibe: '帮助组织实现敏捷转型', description: '精通组织级敏捷转型', detail: '具备丰富的组织级敏捷转型经验，精通Scrum/Kanban/SAFe等敏捷框架，能帮助团队和组织建立敏捷文化、优化工作流程、提升交付能力。' },
  { id: '129', name: '技术项目经理', slug: 'technical-project-manager', division: '项目管理', emoji: '⚙️', vibe: '用技术思维管理复杂项目', description: '精通技术项目管理和技术沟通', detail: '兼具技术背景和项目管理能力，精通技术架构评估、技术风险管理、技术团队协调，能有效管理复杂的技术项目。' },
  { id: '130', name: '产品运营经理', slug: 'product-operations-manager', division: '项目管理', emoji: '📊', vibe: '连接产品、技术和业务的桥梁', description: '精通产品运营和跨团队协作', detail: '精通产品运营全流程，包括产品上线、数据监控、用户反馈收集、功能迭代等，能高效协调产品、技术、运营等多团队协作。' },
  { id: '131', name: 'PMP认证顾问', slug: 'pmp-consultant', division: '项目管理', emoji: '🎓', vibe: '用专业方法论提升项目成功率', description: '精通PMP项目管理体系', detail: '精通PMBOK项目管理知识体系，能为组织提供项目管理咨询、流程优化、工具选型、人员培训等服务，提升项目管理成熟度。' },
  { id: '132', name: 'IT项目管理专家', slug: 'it-pm-expert', division: '项目管理', emoji: '💻', vibe: '管理IT项目的全生命周期', description: '精通IT项目管理和交付', detail: '精通IT项目全生命周期管理，包括需求分析、系统设计、开发实施、测试验收、运维交付等阶段，能确保IT项目按时保质交付。' },
  { id: '133', name: '风险管理顾问', slug: 'risk-management-consultant', division: '项目管理', emoji: '🛡️', vibe: '提前识别和应对项目风险', description: '精通项目风险管理方法论', detail: '精通风险识别、评估、应对、监控等风险管理全流程，能建立项目风险管理体系，制定风险应对策略，降低项目失败概率。' },
  { id: '134', name: '项目集管理专家', slug: 'program-manager', division: '项目管理', emoji: '🔗', vibe: '协调多个项目实现战略目标', description: '精通项目集管理和战略对齐', detail: '精通项目集管理方法论，能协调多个相关项目实现战略目标，管理跨项目的依赖关系、资源共享、收益实现，确保整体价值最大化。' },
  { id: '135', name: 'DevOps项目经理', slug: 'devops-pm', division: '项目管理', emoji: '🔄', vibe: '让DevOps实践落地生根', description: '精通DevOps流程和团队协作', detail: '精通DevOps文化、实践和工具链，能推动CI/CD流程建设、自动化测试、基础设施即代码等DevOps实践落地，提升研发效能。' },

  // === 销售 (Sales) ===
  { id: '136', name: '销售总监', slug: 'sales-director', division: '销售', emoji: '📈', vibe: '带领团队达成销售目标', description: '精通销售策略和团队管理', detail: '具备丰富的销售管理经验，精通销售策略制定、团队建设、业绩管理、客户关系维护，能带领销售团队持续达成和超越业绩目标。' },
  { id: '137', name: '企业销售顾问', slug: 'enterprise-sales-consultant', division: '销售', emoji: '🏢', vibe: '为大客户创造长期价值', description: '精通B2B大客户销售', detail: '精通大客户销售方法论(如SPIN/Challenger)，能识别决策链、建立多层客户关系、制定解决方案、谈判签约，实现大客户的战略合作。' },
  { id: '138', name: '销售开发代表', slug: 'sales-development-representative', division: '销售', emoji: '📞', vibe: '精准筛选高质量销售线索', description: '精通潜在客户开发和资质筛选', detail: '精通cold calling/outreach邮件/LinkedIn拓展等潜在客户开发方式，能快速筛选合格的销售线索(SQL)，为销售漏斗注入高质量商机。' },
  { id: '139', name: '客户成功经理', slug: 'customer-success-manager', division: '销售', emoji: '🤝', vibe: '帮助客户成功，实现续约增长', description: '精通客户成功和续约管理', detail: '精通客户成功方法论，能制定客户onboarding流程、健康度评估、使用分析、续约策略，确保客户实现业务价值并持续续费。' },
  { id: '140', name: 'SaaS销售专家', slug: 'saas-sales-specialist', division: '销售', emoji: '☁️', vibe: '用SaaS思维革新销售模式', description: '精通SaaS销售和订阅模式', detail: '精通SaaS销售方法论，理解ARR/MRR/Churn/LTV等核心指标，能设计高效的SaaS销售流程，实现可预测的收入增长。' },
  { id: '141', name: '渠道销售经理', slug: 'channel-sales-manager', division: '销售', emoji: '🔗', vibe: '通过渠道伙伴扩大市场覆盖', description: '精通渠道建设和管理', detail: '精通渠道销售策略，能设计渠道体系、招募和培训渠道伙伴、制定激励政策、管理渠道冲突，通过渠道杠杆实现规模化销售。' },
  { id: '142', name: '售前技术顾问', slug: 'presales-consultant', division: '销售', emoji: '🔧', vibe: '用技术方案赢得客户信任', description: '精通产品演示和技术方案设计', detail: '兼具技术背景和销售能力，精通产品演示、技术方案设计、POC测试、招投标支持，能将产品技术优势转化为客户认可的解决方案。' },
  { id: '143', name: '定价策略师', slug: 'pricing-strategist', division: '销售', emoji: '💰', vibe: '制定最优化的价格策略', description: '精通定价模型和价值定价', detail: '精通价值定价、竞争定价、分层定价等定价策略，能通过市场调研、成本分析、客户支付意愿分析，制定最大化收入的定价方案。' },
  { id: '144', name: '销售培训师', slug: 'sales-trainer', division: '销售', emoji: '📚', vibe: '打造高战斗力的销售团队', description: '精通销售技能培训和方法论', detail: '精通销售方法论(SPIN/Challenger/MEDDIC等)，能设计和实施销售培训课程，提升团队的销售技巧、产品知识、谈判能力。' },
  { id: '145', name: '关键客户经理', slug: 'key-account-manager', division: '销售', emoji: '⭐', vibe: '深耕核心客户，实现持续增长', description: '精通关键客户关系管理', detail: '精通关键客户管理(KAM)方法论，能建立深层客户关系、挖掘交叉销售机会、制定年度合作计划、管理客户满意度，实现客户价值最大化。' },

  // === 安全 (Security) ===
  { id: '146', name: '网络安全工程师', slug: 'network-security-engineer', division: '安全', emoji: '🛡️', vibe: '构建铜墙铁壁的网络防护', description: '精通网络安全防护技术', detail: '精通防火墙/IDS/IPS/WAF等网络安全设备和技术，能设计和部署网络安全架构，监控网络威胁，响应安全事件，保障企业网络安全。' },
  { id: '147', name: '渗透测试专家', slug: 'penetration-tester', division: '安全', emoji: '🔓', vibe: '以攻击者的视角发现安全漏洞', description: '精通渗透测试和漏洞挖掘', detail: '精通渗透测试方法论和工具(Metasploit/Burp Suite/Nmap等)，能模拟真实攻击场景，发现Web应用、网络系统、API接口的安全漏洞。' },
  { id: '148', name: '安全架构师', slug: 'security-architect', division: '安全', emoji: '🏛️', vibe: '设计安全的企业IT架构', description: '精通企业安全架构设计', detail: '具备全面的安全架构设计能力，精通零信任架构、IAM、加密体系、安全合规等，能设计符合业务需求和安全标准的企业安全架构。' },
  { id: '149', name: 'SOC分析师', slug: 'soc-analyst', division: '安全', emoji: '🔍', vibe: '7x24小时守护网络安全', description: '精通安全监控和事件响应', detail: '精通SIEM/SOAR等安全监控工具，能进行安全事件监控、威胁检测、事件调查、应急响应，确保安全事件得到及时有效的处理。' },
  { id: '150', name: '安全合规顾问', slug: 'compliance-consultant', division: '安全', emoji: '⚖️', vibe: '确保企业安全合规', description: '精通安全合规标准和审计', detail: '精通ISO 27001/SOC 2/PCI DSS/GDPR等安全合规标准，能帮助组织建立合规体系、进行合规评估、准备合规审计，降低合规风险。' },
  { id: '151', name: '恶意软件分析师', slug: 'malware-analyst', division: '安全', emoji: '🦠', vibe: '解剖恶意软件，化威胁为情报', description: '精通恶意软件分析和逆向工程', detail: '精通静态分析/动态分析/逆向工程等恶意软件分析技术，能分析恶意软件的行为特征、传播机制、规避技术，为威胁情报和防御策略提供支撑。' },
  { id: '152', name: '云安全工程师', slug: 'cloud-security-engineer', division: '安全', emoji: '☁️', vibe: '保障云环境的安全合规', description: '精通云安全配置和监控', detail: '精通AWS/Azure/GCP云安全服务，能进行云环境安全评估、安全配置加固、云安全监控、IAM策略管理，保障云上资产的安全性。' },
  { id: '153', name: '数据安全专家', slug: 'data-security-specialist', division: '安全', emoji: '🔐', vibe: '保护数据资产的全生命周期安全', description: '精通数据加密和隐私保护', detail: '精通数据分类分级、加密技术、数据脱敏、DLP(数据防泄漏)等数据安全技术，能设计数据安全策略，保护企业核心数据资产。' },
  { id: '154', name: '红队操作员', slug: 'red-team-operator', division: '安全', emoji: '🔴', vibe: '模拟高级威胁，检验防御能力', description: '精通高级持续性威胁模拟', detail: '精通MITRE ATT&CK框架，能模拟APT攻击场景，进行社会工程学攻击、横向移动、持久化等高级攻击技术，全面检验企业的安全防御能力。' },
  { id: '155', name: '安全开发工程师', slug: 'secdevops-engineer', division: '安全', emoji: '🔄', vibe: '将安全融入开发全流程', description: '精通DevSecOps实践', detail: '精通DevSecOps理念和实践，能将安全测试(静态分析/动态分析/依赖检查)集成到CI/CD流水线中，实现安全左移，降低安全风险。' },

  // === 空间计算 (Spatial Computing) ===
  { id: '156', name: 'AR开发工程师', slug: 'ar-developer', division: '空间计算', emoji: '📱', vibe: '将数字信息融入现实世界', description: '精通ARKit/ARCore开发', detail: '精通ARKit/ARCore/Vuforia等AR开发框架，能实现图像识别、平面检测、空间锚点、光照估计等AR核心功能，构建高质量的增强现实应用。' },
  { id: '157', name: 'VR开发工程师', slug: 'vr-developer', division: '空间计算', emoji: '🥽', vibe: '创造令人沉浸的虚拟世界', description: '精通Unity/Unreal VR开发', detail: '精通Unity/Unreal Engine VR开发，精通交互设计、空间音频、手部追踪、眼动追踪等VR核心技术，能为Meta Quest/Vision Pro等平台开发沉浸式VR应用。' },
  { id: '158', name: 'MR混合现实专家', slug: 'mr-specialist', division: '空间计算', emoji: '🔮', vibe: '融合现实与虚拟的无缝体验', description: '精通混合现实技术开发', detail: '精通混合现实(MR)技术，理解空间计算、环境理解、虚实融合等核心概念，能为HoloLens/Vision Pro等设备开发高质量的混合现实应用。' },
  { id: '159', name: '3D场景建模师', slug: '3d-scene-modeler', division: '空间计算', emoji: '🏔️', vibe: '构建逼真的三维数字世界', description: '精通3D场景和环境建模', detail: '精通Blender/Maya/3ds Max等3D建模软件，能进行场景建模、材质制作、灯光设计、环境渲染，为AR/VR/MR应用创建高质量的3D内容。' },
  { id: '160', name: '空间交互设计师', slug: 'spatial-interaction-designer', division: '空间计算', emoji: '🤝', vibe: '设计直觉化的空间交互方式', description: '精通空间交互设计原则', detail: '精通空间交互设计，理解6DoF交互、手势交互、语音交互、眼动交互等空间交互方式，能设计自然、直觉、高效的空间交互体验。' },
  { id: '161', name: '计算机视觉工程师', slug: 'computer-vision-engineer', division: '空间计算', emoji: '👁️', vibe: '让机器理解和感知视觉世界', description: '精通计算机视觉算法开发', detail: '精通OpenCV/深度学习视觉模型，能实现目标检测、图像分割、姿态估计、SLAM等计算机视觉核心算法，为空间计算提供视觉感知能力。' },
  { id: '162', name: '空间音频工程师', slug: 'spatial-audio-engineer', division: '空间计算', emoji: '🔊', vibe: '用声音构建空间感和沉浸感', description: '精通空间音频技术', detail: '精通Ambisonics/双耳渲染/声学模拟等空间音频技术，能为AR/VR/MR应用设计沉浸式空间音频体验，增强虚拟环境的真实感。' },
  { id: '163', name: '数字孪生工程师', slug: 'digital-twin-engineer', division: '空间计算', emoji: '🪞', vibe: '构建物理世界的数字镜像', description: '精通数字孪生平台开发', detail: '精通数字孪生技术，能构建物理实体的数字模型，实现实时数据同步、模拟仿真、预测分析等功能，为智慧城市、智能制造等场景提供支撑。' },
  { id: '164', name: 'XR产品经理', slug: 'xr-product-manager', division: '空间计算', emoji: '📋', vibe: '定义下一代计算平台的产品方向', description: '精通XR产品设计和策略', detail: '深入理解XR行业趋势和技术发展，精通XR产品的需求分析、场景设计、用户体验优化，能定义和推动有影响力的XR产品方向。' },
  { id: '165', name: '全息投影工程师', slug: 'holographic-engineer', division: '空间计算', emoji: '✨', vibe: '让全息显示从科幻走向现实', description: '精通全息显示和光场技术', detail: '精通全息显示原理和光场技术，能开发全息投影系统、光场相机、体积显示等前沿技术，推动全息通信和全息交互的商业化应用。' },

  // === 专业领域 (Specialized) ===
  { id: '166', name: '法律科技顾问', slug: 'legaltech-consultant', division: '专业领域', emoji: '⚖️', vibe: '用技术革新法律服务', description: '精通法律科技和合规系统', detail: '精通法律科技应用，包括合同智能审查、法律知识图谱、合规自动化、电子签名等，能帮助法律部门和律所提升效率和降低风险。' },
  { id: '167', name: 'HR科技顾问', slug: 'hrtech-consultant', division: '专业领域', emoji: '👥', vibe: '用技术重塑人力资源管理', description: '精通HR数字化转型', detail: '精通人力资源数字化，包括HRIS系统、人才招聘平台、绩效管理系统、员工体验平台等，能帮助组织提升人力资源管理效率。' },
  { id: '168', name: '农业科技顾问', slug: 'agritech-consultant', division: '专业领域', emoji: '🌾', vibe: '用技术赋能现代农业', description: '精通智慧农业技术应用', detail: '精通精准农业、农业物联网、无人机植保、AI病虫害识别等农业技术，能帮助农业企业实现数字化转型，提升农业生产效率。' },
  { id: '169', name: '汽车科技顾问', slug: 'automotive-tech-consultant', division: '专业领域', emoji: '🚗', vibe: '推动智能出行的未来', description: '精通智能汽车和自动驾驶技术', detail: '精通自动驾驶、车联网V2X、智能座舱、OTA升级等智能汽车核心技术，能为汽车OEM和Tier 1提供技术咨询和产品方案。' },
  { id: '170', name: '能源科技顾问', slug: 'energytech-consultant', division: '专业领域', emoji: '⚡', vibe: '用技术推动能源转型', description: '精通新能源和能源管理系统', detail: '精通光伏/储能/充电桩等新能源技术，精通能源管理系统(EMS)、微电网、碳交易平台等，能帮助能源企业实现数字化和低碳化。' },
  { id: '171', name: '教育科技顾问', slug: 'edtech-consultant', division: '专业领域', emoji: '📚', vibe: '用技术革新教育方式', description: '精通教育科技产品和平台', detail: '精通在线教育、自适应学习、AI教学助手、学习分析等教育科技应用，能帮助教育机构和企业设计和实施教育数字化转型方案。' },
  { id: '172', name: '物流科技顾问', slug: 'logtech-consultant', division: '专业领域', emoji: '🚚', vibe: '用技术优化供应链效率', description: '精通物流数字化和供应链优化', detail: '精通仓储管理系统(WMS)、运输管理系统(TMS)、供应链可视化、智能调度等物流技术，能帮助物流企业实现数字化和智能化升级。' },
  { id: '173', name: '零售科技顾问', slug: 'retailtech-consultant', division: '专业领域', emoji: '🛒', vibe: '用技术重塑零售体验', description: '精通新零售和零售数字化', detail: '精通全渠道零售、智能推荐、库存优化、会员运营、门店数字化等零售技术，能帮助零售企业实现线上线下融合的数字化转型。' },
  { id: '174', name: '网络安全研究员', slug: 'security-researcher', division: '专业领域', emoji: '🔬', vibe: '发现和研究前沿安全威胁', description: '精通安全漏洞研究和威胁分析', detail: '精通安全漏洞挖掘、0day研究、威胁情报分析、攻击技术研究等安全研究领域，能发现新的攻击向量和防御方法。' },
  { id: '175', name: '密码学专家', slug: 'cryptography-expert', division: '专业领域', emoji: '🔐', vibe: '用数学构建安全的基石', description: '精通密码学理论和应用', detail: '精通对称加密、非对称加密、哈希函数、数字签名、零知识证明等密码学技术，能设计和评估安全加密方案。' },
  { id: '176', name: '量子计算研究员', slug: 'quantum-computing-researcher', division: '专业领域', emoji: '⚛️', vibe: '探索量子计算的无限可能', description: '精通量子计算理论和编程', detail: '精通量子比特、量子门、量子算法等量子计算基础理论，精通Qiskit/Cirq等量子编程框架，能设计和实现量子计算实验和原型。' },
  { id: '177', name: '机器人工程师', slug: 'robotics-engineer', division: '专业领域', emoji: '🤖', vibe: '让机器人完成复杂任务', description: '精通机器人系统设计和控制', detail: '精通机器人运动学、控制算法、传感器融合、路径规划等核心技术，能设计和开发工业机器人、服务机器人、协作机器人等系统。' },
  { id: '178', name: '数字遗产顾问', slug: 'digital-legacy-consultant', division: '专业领域', emoji: '🏛️', vibe: '守护数字世界的永恒记忆', description: '精通数字遗产管理和保护', detail: '精通数字资产确权、数字遗产规划、NFT版权保护、元宇宙资产继承等新兴领域，能为个人和企业提供数字遗产管理咨询服务。' },
  { id: '179', name: '可持续发展顾问', slug: 'sustainability-consultant', division: '专业领域', emoji: '🌱', vibe: '推动商业与环境的和谐共生', description: '精通ESG和可持续发展战略', detail: '精通ESG(环境、社会、治理)评估框架、碳中和路径规划、绿色供应链管理、可持续报告编制等，能帮助企业制定和实施可持续发展战略。' },
  { id: '180', name: '元宇宙架构师', slug: 'metaverse-architect', division: '专业领域', emoji: '🌌', vibe: '构建下一代互联网的蓝图', description: '精通元宇宙技术架构设计', detail: '精通元宇宙核心技术栈，包括虚拟世界引擎、数字身份、经济系统、社交机制等，能设计开放、可互操作的元宇宙平台架构。' },

  // === 支持 (Support) ===
  { id: '181', name: '技术支持工程师', slug: 'tech-support-engineer', division: '支持', emoji: '🔧', vibe: '快速解决技术问题', description: '精通产品技术支持和故障排除', detail: '具备丰富的技术支持经验，精通产品功能、系统配置、故障排除等技术支持工作，能快速定位和解决用户遇到的技术问题。' },
  { id: '182', name: '客户成功顾问', slug: 'customer-success-consultant', division: '支持', emoji: '🤝', vibe: '帮助客户最大化产品价值', description: '精通客户成功策略和实践', detail: '精通客户成功方法论，能制定客户onboarding流程、健康度评估模型、续约策略，帮助客户实现业务目标并持续使用产品。' },
  { id: '183', name: '知识库管理员', slug: 'knowledge-base-admin', division: '支持', emoji: '📚', vibe: '构建智能的知识管理体系', description: '精通知识库建设和维护', detail: '精通知识库系统(Confluence/Notion等)，能设计知识分类体系、创建高质量的技术文档和FAQ、维护知识库的时效性和准确性。' },
  { id: '184', name: '用户培训师', slug: 'user-trainer', division: '支持', emoji: '🎓', vibe: '让用户快速掌握产品使用', description: '精通用户培训和课程设计', detail: '精通培训课程设计和交付，能制作培训材料、设计学习路径、进行现场/在线培训，帮助用户快速上手并高效使用产品。' },
  { id: '185', name: 'SaaS运维工程师', slug: 'saas-ops-engineer', division: '支持', emoji: '☁️', vibe: '保障SaaS服务的稳定运行', description: '精通SaaS服务运维和监控', detail: '精通SaaS服务的运维管理，包括服务监控、告警处理、容量规划、故障恢复、SLA保障等，确保SaaS服务的高可用性和性能。' },
  { id: '186', name: 'IT服务台主管', slug: 'it-service-desk-lead', division: '支持', emoji: '📞', vibe: '高效解决IT服务请求', description: '精通ITIL服务管理体系', detail: '精通ITIL服务管理框架，能管理IT服务台运营、事件管理、问题管理、变更管理等IT服务流程，确保IT服务质量和用户满意度。' },
  { id: '187', name: '现场服务工程师', slug: 'field-service-engineer', division: '支持', emoji: '🔧', vibe: '到现场解决客户问题', description: '精通现场设备安装和维护', detail: '具备丰富的现场服务经验，能进行设备安装调试、现场故障排除、定期维护保养、客户技术培训等现场服务工作。' },
  { id: '188', name: '数据恢复专家', slug: 'data-recovery-specialist', division: '支持', emoji: '💾', vibe: '挽救丢失的数据', description: '精通数据恢复技术和流程', detail: '精通各类存储介质(硬盘/SSD/RAID/云存储)的数据恢复技术，能进行数据丢失诊断、数据恢复方案设计和执行，最大限度挽回数据损失。' },
  { id: '189', name: '远程协助专家', slug: 'remote-assistance-specialist', division: '支持', emoji: '🌐', vibe: '远程解决技术难题', description: '精通远程支持工具和技术', detail: '精通TeamViewer/AnyDesk等远程支持工具，能通过远程方式快速诊断和解决用户的技术问题，提供高质量的远程技术支持服务。' },
  { id: '190', name: '服务质量经理', slug: 'service-quality-manager', division: '支持', emoji: '📊', vibe: '持续提升服务质量和客户满意度', description: '精通服务质量管理和改进', detail: '精通服务质量管理体系，能进行客户满意度调研、服务质量审计、流程改进、团队绩效管理，持续提升服务团队的专业能力。' },

  // === 测试 (Testing) ===
  { id: '191', name: 'QA测试工程师', slug: 'qa-test-engineer', division: '测试', emoji: '🧪', vibe: '用系统化测试保障产品质量', description: '精通软件测试方法和流程', detail: '精通软件测试全生命周期，能设计测试计划、编写测试用例、执行功能测试/回归测试、提交缺陷报告、验证修复，确保产品质量。' },
  { id: '192', name: '自动化测试工程师', slug: 'automation-test-engineer', division: '测试', emoji: '🤖', vibe: '让测试变得更高效更可靠', description: '精通自动化测试框架开发', detail: '精通Selenium/Cypress/Playwright等自动化测试框架，能设计自动化测试架构、编写自动化测试脚本、集成到CI/CD流水线中。' },
  { id: '193', name: '性能测试工程师', slug: 'performance-test-engineer', division: '测试', emoji: '⚡', vibe: '确保系统在高负载下依然稳定', description: '精通性能测试和调优', detail: '精通JMeter/Locust/Gatling等性能测试工具，能设计性能测试方案、执行压力测试/负载测试/稳定性测试、分析性能瓶颈、提供优化建议。' },
  { id: '194', name: '安全测试工程师', slug: 'security-test-engineer', division: '测试', emoji: '🛡️', vibe: '从测试角度发现安全漏洞', description: '精通安全测试技术', detail: '精通OWASP测试指南，能进行Web应用安全测试、API安全测试、渗透测试，发现SQL注入/XSS/CSRF等常见安全漏洞。' },
  { id: '195', name: '移动端测试工程师', slug: 'mobile-test-engineer', division: '测试', emoji: '📱', vibe: '保障移动端产品的品质', description: '精通移动应用测试技术', detail: '精通Appium/Espresso/XCTest等移动测试框架，能进行iOS/Android应用的功能测试、兼容性测试、性能测试、自动化测试。' },
  { id: '196', name: 'API测试工程师', slug: 'api-test-engineer', division: '测试', emoji: '🔗', vibe: '确保API接口稳定可靠', description: '精通API测试和契约测试', detail: '精通Postman/RestAssured/Pytest等API测试工具，能进行API功能测试、性能测试、安全测试、契约测试，确保API接口的质量。' },
  { id: '197', name: '测试架构师', slug: 'test-architect', division: '测试', emoji: '🏛️', vibe: '设计高效的测试基础设施', description: '精通测试架构设计和方法论', detail: '具备全面的测试架构设计能力，精通测试策略、测试框架设计、测试数据管理、测试环境管理，能构建可持续演进的测试基础设施。' },
  { id: '198', name: '混沌工程专家', slug: 'chaos-engineering-specialist', division: '测试', emoji: '💥', vibe: '主动注入故障，检验系统韧性', description: '精通混沌工程实践', detail: '精通Chaos Monkey/LitmusChaos等混沌工程工具，能设计和执行故障注入实验，验证系统的容错能力和恢复机制，提升系统韧性。' },
  { id: '199', name: '游戏测试工程师', slug: 'game-test-engineer', division: '测试', emoji: '🎮', vibe: '确保游戏体验完美无瑕', description: '精通游戏测试方法', detail: '精通游戏功能测试、兼容性测试、性能测试、多人联机测试等游戏测试方法，能设计全面的测试策略，确保游戏发布品质。' },
  { id: '200', name: '可访问性测试专家', slug: 'accessibility-tester', division: '测试', emoji: '♿', vibe: '确保产品对所有人可用', description: '精通Web可访问性测试标准', detail: '精通WCAG 2.1可访问性标准，精通屏幕阅读器/键盘导航/色彩对比等辅助技术，能进行无障碍测试并提供修复建议，确保产品对残障用户友好。' },

  // === 营销 (Marketing) - 续 ===
  { id: '201', name: '视频营销专家', slug: 'video-marketing-specialist', division: '营销', emoji: '🎬', vibe: '用视频讲述品牌故事', description: '精通视频内容策略和制作', detail: '精通视频内容策划、拍摄、剪辑、发布全流程，精通YouTube/B站/抖音等视频平台运营策略，能制作吸引人的品牌视频内容。' },
  { id: '202', name: '播客营销专家', slug: 'podcast-marketing-specialist', division: '营销', emoji: '🎙️', vibe: '用声音建立品牌影响力', description: '精通播客内容策划和运营', detail: '精通播客内容策划、制作、分发、推广全流程，能帮助品牌建立播客内容矩阵，通过音频内容触达和影响目标受众。' },
  { id: '203', name: '线下活动策划师', slug: 'offline-event-planner', division: '营销', emoji: '🎪', vibe: '打造沉浸式的线下体验', description: '精通线下活动策划和执行', detail: '精通线下活动策划全流程，包括场地选择、活动设计、供应商管理、现场执行、活动复盘等，能打造有影响力的品牌线下活动。' },
  { id: '204', name: '公关传播经理', slug: 'pr-communications-manager', division: '营销', emoji: '📰', vibe: '管理品牌声誉和媒体关系', description: '精通公关策略和媒体关系', detail: '精通公关策略制定、媒体关系维护、新闻稿撰写、危机公关处理等公关核心能力，能有效管理品牌声誉和对外传播。' },
  { id: '205', name: '口碑营销专家', slug: 'word-of-mouth-specialist', division: '营销', emoji: '💬', vibe: '让用户自发传播品牌', description: '精通口碑营销和用户推荐', detail: '精通口碑营销策略，能设计用户推荐计划、UGC激励机制、社群传播策略，通过口碑效应实现低成本的用户增长。' },
  { id: '206', name: '联营营销专家', slug: 'affiliate-marketing-specialist', division: '营销', emoji: '🤝', vibe: '通过合作伙伴扩大销售网络', description: '精通联营营销策略和管理', detail: '精通联营营销计划设计、合作伙伴招募和管理、佣金结构设计、效果跟踪和优化，能通过联营渠道实现规模化销售。' },
  { id: '207', name: '本地化营销专家', slug: 'localization-marketing-specialist', division: '营销', emoji: '🌍', vibe: '让品牌在每个市场都引发共鸣', description: '精通多市场本地化营销', detail: '精通多市场营销策略，理解不同市场的文化差异和用户行为，能制定适合当地市场的营销策略和内容，实现品牌的全球化和本地化平衡。' },
  { id: '208', name: '社区运营经理', slug: 'community-manager', division: '营销', emoji: '👥', vibe: '构建有活力的品牌社区', description: '精通社区建设和用户运营', detail: '精通社区运营策略，能建设品牌社区、培养KOC、策划社区活动、管理社区内容，通过社区驱动品牌认知和用户留存。' },

  // === 金融 (Finance) - 续 ===
  { id: '209', name: '资产管理经理', slug: 'asset-manager', division: '金融', emoji: '💼', vibe: '专业管理客户资产', description: '精通资产配置和投资组合', detail: '精通各类资产的估值和投资分析，能根据客户风险偏好和投资目标，制定个性化的资产配置方案，实现资产的保值增值。' },
  { id: '210', name: '并购顾问', slug: 'ma-advisor', division: '金融', emoji: '🤝', vibe: '促成战略性的企业并购', description: '精通并购交易全流程', detail: '精通并购交易的全流程，包括目标筛选、尽职调查、估值谈判、交易结构设计、整合规划等，能促成战略性的企业并购交易。' },
  { id: '211', name: '基金管理经理', slug: 'fund-operations-manager', division: '金融', emoji: '📊', vibe: '确保基金运营合规高效', description: '精通基金运营和合规管理', detail: '精通基金运营全流程，包括净值计算、份额登记、信息披露、合规监控等，确保基金运营的准确性和合规性。' },
  { id: '212', name: '另类投资顾问', slug: 'alternative-investment-advisor', division: '金融', emoji: '💎', vibe: '发掘传统之外的投资机会', description: '精通另类投资策略', detail: '精通私募股权、对冲基金、房地产投资、艺术品投资等另类投资领域，能为高净值客户提供多元化的投资配置建议。' },
  { id: '213', name: '反洗钱专家', slug: 'aml-specialist', division: '金融', emoji: '🔍', vibe: '识别和防范金融犯罪', description: '精通反洗钱法规和监控系统', detail: '精通反洗钱(AML)法规和合规要求，精通KYC/交易监控/可疑交易报告等反洗钱核心流程，能帮助金融机构建立完善的反洗钱体系。' },
  { id: '214', name: '信贷风控经理', slug: 'credit-risk-manager', division: '金融', emoji: '⚖️', vibe: '精准评估信用风险', description: '精通信用评估和风控模型', detail: '精通信用评分模型、信贷审批流程、贷后管理等信贷风控核心能力，能设计和优化信贷风控策略，平衡风险和收益。' },
  { id: '215', name: '金融产品经理', slug: 'financial-product-manager', division: '金融', emoji: '📋', vibe: '设计用户喜爱的金融产品', description: '精通金融产品设计和用户体验', detail: '精通金融产品(存款/理财/保险/贷款等)的设计逻辑，理解监管要求，能设计用户友好且合规的金融产品，提升用户金融体验。' },
  { id: '216', name: '金融科技架构师', slug: 'fintech-architect', division: '金融', emoji: '🏗️', vibe: '构建高性能的金融系统架构', description: '精通金融系统架构设计', detail: '精通金融系统的核心架构设计，包括交易系统、清算系统、风控系统等，能设计高可用、低延迟、安全合规的金融科技架构。' },

  // === 工程 (Engineering) - 续 ===
  { id: '217', name: '前端架构师', slug: 'frontend-architect', division: '工程', emoji: '🏛️', vibe: '设计可扩展的前端技术架构', description: '精通前端架构设计和工程化', detail: '精通大型前端项目架构设计，包括微前端、构建优化、性能监控、设计系统等前端架构核心能力，能制定前端技术战略。' },
  { id: '218', name: 'SRE工程师', slug: 'sre-engineer', division: '工程', emoji: '🔄', vibe: '用软件工程方法解决运维问题', description: '精通SRE实践和可观测性', detail: '精通SRE核心实践，包括SLI/SLO/Error Budget、可观测性(日志/指标/链路追踪)、故障管理、容量规划等，保障系统可靠性。' },
  { id: '219', name: '平台工程师', slug: 'platform-engineer', division: '工程', emoji: '🏗️', vibe: '构建开发者友好的内部平台', description: '精通平台工程和开发者体验', detail: '精通平台工程实践，能设计和构建内部开发者平台(IDP)，包括CI/CD平台、基础设施即服务、开发者工具链等，提升研发效能。' },
  { id: '220', name: '数据平台工程师', slug: 'data-platform-engineer', division: '工程', emoji: '📊', vibe: '构建强大的数据处理平台', description: '精通数据平台架构设计', detail: '精通大数据平台架构，包括数据湖/数据仓库/数据中台/实时计算等，能设计和构建可扩展的数据处理平台。' },
  { id: '221', name: 'AI推理优化工程师', slug: 'ai-inference-engineer', division: '工程', emoji: '⚡', vibe: '让AI模型跑得更快更省', description: '精通模型推理优化技术', detail: '精通模型量化/蒸馏/剪枝/推理引擎优化等技术，能将AI模型的推理速度提升数倍，降低计算成本，支持大规模在线服务。' },
  { id: '222', name: 'Prompt工程师', slug: 'prompt-engineer', division: '工程', emoji: '💡', vibe: '用精准的提示词释放AI潜力', description: '精通LLM提示词工程', detail: '精通大语言模型的提示词设计和优化，包括零样本/少样本学习、Chain-of-Thought推理、RAG增强等技术，能设计高效的AI应用提示词策略。' },
  { id: '223', name: 'Rust后端工程师', slug: 'rust-backend-engineer', division: '工程', emoji: '🦀', vibe: '用Rust构建高性能后端服务', description: '精通Rust后端开发', detail: '精通Rust语言和Tokio/Actix-web等异步运行时，能构建高性能、内存安全的后端微服务、CLI工具和WebAssembly模块。' },
  { id: '224', name: 'Go微服务工程师', slug: 'go-microservice-engineer', division: '工程', emoji: '🐹', vibe: '用Go构建云原生微服务', description: '精通Go微服务开发', detail: '精通Go语言和微服务架构，精通gRPC/Protobuf、服务发现、分布式追踪等微服务核心技术，能构建高性能、可扩展的微服务系统。' },
  { id: '225', name: 'Flutter开发工程师', slug: 'flutter-developer', division: '工程', emoji: '🦋', vibe: '用一套代码覆盖全平台', description: '精通Flutter跨平台开发', detail: '精通Flutter/Dart语言和生态系统，能开发高质量的iOS/Android/Web/桌面跨平台应用，精通Widget体系、状态管理、平台集成等。' },
  { id: '226', name: '微前端架构师', slug: 'microfrontend-architect', division: '工程', emoji: '🧩', vibe: '让大型前端项目模块化协作', description: '精通微前端架构设计', detail: '精通微前端架构理论和实践，精通qiankun/Module Federation/Web Components等微前端方案，能设计可独立开发部署的微前端架构。' },

  // === 专业领域 (Specialized) - 续 ===
  { id: '227', name: '航空科技顾问', slug: 'aviation-tech-consultant', division: '专业领域', emoji: '✈️', vibe: '推动航空数字化转型', description: '精通航空IT系统和数字化', detail: '精通航空MRO系统、航班运行控制、旅客服务系统、空管系统等航空核心IT系统，能帮助航空企业实现数字化转型和智能化升级。' },
  { id: '228', name: '海洋科技顾问', slug: 'marinetech-consultant', division: '专业领域', emoji: '🌊', vibe: '用技术探索海洋奥秘', description: '精通海洋数据和海洋工程', detail: '精通海洋观测系统、海洋数据分析、水下机器人、海洋牧场等海洋科技领域，能帮助海洋相关企业和研究机构实现技术升级。' },
  { id: '229', name: '材料科学顾问', slug: 'materials-science-consultant', division: '专业领域', emoji: '🧪', vibe: '用AI加速新材料发现', description: '精通材料信息学和计算材料学', detail: '精通材料基因组计划、高通量计算、机器学习辅助材料设计等材料信息学方法，能加速新材料的发现和优化过程。' },
  { id: '230', name: '食品安全顾问', slug: 'food-safety-consultant', division: '专业领域', emoji: '🍎', vibe: '用技术保障食品安全', description: '精通食品安全追溯和检测', detail: '精通食品安全管理体系(HACCP/ISO 22000)、区块链追溯、AI视觉检测、传感器监测等技术，能帮助食品企业建立完善的食品安全保障体系。' },
  { id: '231', name: '城市大脑架构师', slug: 'smart-city-architect', division: '专业领域', emoji: '🏙️', vibe: '让城市更智能更宜居', description: '精通智慧城市顶层设计', detail: '精通智慧城市的顶层设计方法论，能整合交通、能源、环保、安防等城市子系统，设计城市大脑架构，推动城市数字化治理。' },
  { id: '232', name: '文化遗产数字化专家', slug: 'cultural-heritage-digitizer', division: '专业领域', emoji: '🏛️', vibe: '用技术守护人类文化遗产', description: '精通文化遗产数字化保护', detail: '精通3D扫描、高光谱成像、数字孪生等文化遗产数字化技术，能为博物馆、文物遗址等创建数字化档案和虚拟展览。' },
  { id: '233', name: '体育科技顾问', slug: 'sports-tech-consultant', division: '专业领域', emoji: '⚽', vibe: '用数据提升运动表现', description: '精通运动数据分析和训练', detail: '精通运动捕捉、生理数据分析、战术分析、运动员表现评估等体育科技应用，能帮助运动队和运动员通过数据提升训练和比赛表现。' },
  { id: '234', name: '心理咨询AI顾问', slug: 'mental-health-ai-consultant', division: '专业领域', emoji: '🧠', vibe: '用AI辅助心理健康服务', description: '精通AI在心理健康领域的应用', detail: '精通AI情感分析、自然语言处理在心理咨询中的应用，能设计AI辅助的心理健康筛查、陪伴、干预系统，扩大心理健康服务的可及性。' },
  { id: '235', name: '供应链金融顾问', slug: 'supply-chain-finance-consultant', division: '专业领域', emoji: '🔗', vibe: '用金融科技赋能供应链', description: '精通供应链金融产品和风控', detail: '精通应收账款融资、库存融资、预付款融资等供应链金融产品，精通区块链溯源、智能合约、风控模型等技术在供应链金融中的应用。' },
  { id: '236', name: '数字营销自动化专家', slug: 'marketing-automation-expert', division: '专业领域', emoji: '🤖', vibe: '让营销流程自动化智能化', description: '精通营销自动化平台', detail: '精通HubSpot/Marketo/Pardot等营销自动化平台，能设计和优化自动化营销流程，包括线索培育、个性化触达、行为触发、效果归因等。' },

  // === 测试 (Testing) - 续 ===
  { id: '237', name: '游戏性能测试工程师', slug: 'game-performance-tester', division: '测试', emoji: '🎮', vibe: '确保游戏流畅不卡顿', description: '精通游戏性能测试和分析', detail: '精通游戏帧率测试、内存分析、GPU性能分析、网络延迟测试等游戏性能测试方法，能发现和定位游戏性能瓶颈。' },
  { id: '238', name: '兼容性测试工程师', slug: 'compatibility-tester', division: '测试', emoji: '📱', vibe: '确保产品在所有设备上表现一致', description: '精通跨平台兼容性测试', detail: '精通多浏览器/多设备/多操作系统的兼容性测试，精通Sauce Labs/BrowserStack等云测试平台，能确保产品在各种环境下正常运行。' },
  { id: '239', name: '回归测试专家', slug: 'regression-test-specialist', division: '测试', emoji: '🔄', vibe: '确保新功能不影响已有功能', description: '精通回归测试策略和执行', detail: '精通回归测试策略设计，包括测试用例优先级排序、影响分析、自动化回归测试套件维护，确保每次变更都不会引入新的缺陷。' },
  { id: '240', name: '测试数据工程师', slug: 'test-data-engineer', division: '测试', emoji: '📊', vibe: '为测试提供高质量的测试数据', description: '精通测试数据管理', detail: '精通测试数据生成、脱敏、管理等技术，能设计和维护测试数据工厂、测试数据仓库，确保测试数据的质量和覆盖率。' },

  // === 支持 (Support) - 续 ===
  { id: '241', name: 'IT资产管理专员', slug: 'it-asset-manager', division: '支持', emoji: '💻', vibe: '高效管理IT资产生命周期', description: '精通IT资产管理和优化', detail: '精通IT资产全生命周期管理，包括采购、部署、维护、退役等流程，能优化IT资产使用效率，降低IT成本。' },
  { id: '242', name: '业务连续性顾问', slug: 'bcp-consultant', division: '支持', emoji: '🔄', vibe: '确保业务在灾难中持续运行', description: '精通业务连续性和灾备规划', detail: '精通业务连续性计划(BCP)和灾难恢复计划(DRP)的设计和实施，能帮助组织建立完善的业务连续性管理体系。' },
  { id: '243', name: '变更管理专家', slug: 'change-management-specialist', division: '支持', emoji: '📋', vibe: '让变更可控、风险可管', description: '精通IT变更管理流程', detail: '精通ITIL变更管理流程，能设计变更管理策略、评估变更风险、协调变更实施、监控变更效果，确保变更有序可控。' },
  { id: '244', name: '文档工程师', slug: 'documentation-engineer', division: '支持', emoji: '📝', vibe: '让技术文档清晰易懂', description: '精通技术文档编写和维护', detail: '精通技术文档编写规范，能编写API文档、用户手册、架构文档、运维手册等各类技术文档，确保文档准确、及时、易读。' },
  { id: '245', name: '内部系统培训师', slug: 'internal-system-trainer', division: '支持', emoji: '🎓', vibe: '让员工快速掌握内部系统', description: '精通企业系统培训设计', detail: '精通企业内部系统(ERP/CRM/HRIS等)的功能和使用，能设计和交付系统培训课程，帮助员工快速上手并高效使用内部系统。' },

  // === 空间计算 (Spatial Computing) - 续 ===
  { id: '246', name: '数字人开发工程师', slug: 'digital-human-developer', division: '空间计算', emoji: '🧑', vibe: '创造逼真的虚拟数字人', description: '精通数字人建模和驱动技术', detail: '精通3D数字人建模、面部表情驱动、语音合成、动作捕捉等数字人核心技术，能为虚拟主播、数字员工、虚拟偶像等场景创建高质量的数字人。' },
  { id: '247', name: '光场技术研究员', slug: 'lightfield-researcher', division: '空间计算', emoji: '💡', vibe: '探索下一代显示技术', description: '精通光场显示和捕捉技术', detail: '精通光场相机、光场显示、体积显示等前沿显示技术，能设计和实现新一代的沉浸式显示系统。' },
  { id: '248', name: '手势识别工程师', slug: 'gesture-recognition-engineer', division: '空间计算', emoji: '🤚', vibe: '让手势成为自然的交互方式', description: '精通手势识别和追踪技术', detail: '精通计算机视觉和深度学习手势识别算法，能实现手部关键点检测、手势分类、手势追踪等功能，为空间交互提供自然输入方式。' },
  { id: '249', name: '眼动追踪工程师', slug: 'eye-tracking-engineer', division: '空间计算', emoji: '👁️', vibe: '让设备理解你的视线', description: '精通眼动追踪技术开发', detail: '精通眼动追踪硬件和算法，能实现注视点检测、瞳孔追踪、视线估计、Foveated Rendering等功能，为空间计算提供眼动交互能力。' },
  { id: '250', name: '触觉反馈工程师', slug: 'haptic-feedback-engineer', division: '空间计算', emoji: '✋', vibe: '让虚拟世界有真实的触感', description: '精通触觉反馈技术开发', detail: '精通振动反馈、力反馈、超声波触觉等触觉反馈技术，能设计和实现自然、细腻的触觉体验，增强虚拟交互的真实感。' },

  // === 安全 (Security) - 续 ===
  { id: '251', name: '区块链安全审计师', slug: 'blockchain-security-auditor', division: '安全', emoji: '⛓️', vibe: '守护DeFi和智能合约安全', description: '精通智能合约安全审计', detail: '精通Solidity/Rust等智能合约语言，能审计智能合约代码，发现重入攻击、整数溢出、逻辑漏洞等安全问题，保障DeFi项目安全。' },
  { id: '252', name: 'IoT安全工程师', slug: 'iot-security-engineer', division: '安全', emoji: '📡', vibe: '保障物联网设备的安全', description: '精通IoT设备安全测试', detail: '精通IoT设备固件安全、通信安全、云平台安全等IoT安全领域，能进行IoT设备渗透测试、安全评估、安全加固等。' },
  { id: '253', name: 'AI安全研究员', slug: 'ai-security-researcher', division: '安全', emoji: '🤖', vibe: '研究AI系统的安全风险', description: '精通AI安全和对抗攻击', detail: '精通AI对抗攻击、模型窃取、数据投毒、模型后门等AI安全威胁，能研究和防御AI系统面临的新型安全挑战。' },
  { id: '254', name: '隐私计算工程师', slug: 'privacy-computing-engineer', division: '安全', emoji: '🔐', vibe: '让数据可用不可见', description: '精通隐私计算技术', detail: '精通联邦学习、安全多方计算、差分隐私、同态加密等隐私计算技术，能在保护数据隐私的前提下实现数据的协作分析和价值释放。' },
  { id: '255', name: '安全态势感知专家', slug: 'security-posture-specialist', division: '安全', emoji: '🔭', vibe: '全面掌握企业安全态势', description: '精通安全态势管理和监控', detail: '精通安全态势感知平台(SIEM/SOAR/XDR)的部署和运营，能设计全面的安全监控指标体系，实时掌握企业安全态势。' },

  // === 项目管理 (Project Management) - 续 ===
  { id: '256', name: 'OKR实施顾问', slug: 'okr-consultant', division: '项目管理', emoji: '🎯', vibe: '让团队目标对齐、执行有力', description: '精通OKR目标管理方法论', detail: '精通OKR目标管理方法论，能帮助组织设计OKR体系、进行OKR培训、跟踪OKR执行、评估OKR效果，推动组织战略目标的落地。' },
  { id: '257', name: '精益管理顾问', slug: 'lean-management-consultant', division: '项目管理', emoji: '🔄', vibe: '用精益思维消除浪费提升效率', description: '精通精益管理方法论', detail: '精通精益管理(Lean)方法论，能帮助组织识别和消除浪费、优化工作流程、建立持续改进文化，提升运营效率。' },
  { id: '258', name: '跨文化项目经理', slug: 'cross-cultural-pm', division: '项目管理', emoji: '🌍', vibe: '协调全球团队高效协作', description: '精通跨文化团队管理', detail: '精通跨文化沟通和团队管理，具备多语言能力和国际视野，能协调不同时区、文化背景的团队成员高效协作。' },
  { id: '259', name: '创业孵化器顾问', slug: 'startup-incubator-consultant', division: '项目管理', emoji: '🚀', vibe: '帮助创业团队快速成长', description: '精通创业辅导和项目孵化', detail: '精通创业方法论，包括精益创业、商业画布、产品市场契合等，能为创业团队提供商业计划、融资策略、产品规划等全方位指导。' },
  { id: '260', name: 'IT治理顾问', slug: 'it-governance-consultant', division: '项目管理', emoji: '⚖️', vibe: '建立规范的IT治理体系', description: '精通IT治理和架构管理', detail: '精通COBIT/ITIL等IT治理框架，能帮助组织建立IT治理委员会、制定IT战略、管理IT投资、评估IT绩效，确保IT与业务战略对齐。' },

  // === 补充 (Remaining) ===
  { id: '261', name: '数字孪生产品经理', slug: 'digital-twin-pm', division: '产品', emoji: '🪞', vibe: '将数字孪生技术产品化', description: '精通数字孪生产品设计', detail: '精通数字孪生技术的应用场景和产品设计，能将数字孪生能力封装为易用的产品，为智慧城市、智能制造等场景提供数字化解决方案。' },
  { id: '262', name: '低代码应用顾问', slug: 'lowcode-consultant', division: '专业领域', emoji: '🧩', vibe: '让业务人员也能快速构建应用', description: '精通低代码平台实施', detail: '精通Mendix/OutSystems/Power Platform等低代码平台，能帮助组织评估、选型和实施低代码平台，培训业务人员快速构建企业应用。' },
  { id: '263', name: 'AIGC内容运营专家', slug: 'aigc-content-operations', division: '营销', emoji: '🎨', vibe: '用AI生成内容提升营销效率', description: '精通AIGC内容创作和运营', detail: '精通ChatGPT/Midjourney/Stable Diffusion等AIGC工具，能将AI生成能力融入内容营销流程，大幅提升内容创作效率和质量。' },

  // === 营销 (Marketing) - 补充 ===
  { id: '264', name: '抖音策略师', slug: 'douyin-strategist', division: '营销', emoji: '🎵', vibe: '精通抖音平台内容策略和运营', description: '精通抖音平台内容策略和运营', detail: '深入理解抖音推荐算法和流量机制，精通短视频内容策划、热点追踪、直播运营、DOU+投放等抖音运营全链路，能帮助品牌在抖音实现高效增长。' },
  { id: '265', name: 'B站内容策略师', slug: 'bilibili-content-strategist', division: '营销', emoji: '📺', vibe: '精通B站内容创作和社区运营', description: '精通B站内容创作和社区运营', detail: '深入理解B站社区文化和用户偏好，精通中长视频内容策划、弹幕互动运营、UP主合作、B站广告投放等，能帮助品牌在B站建立深度内容影响力。' },
  { id: '266', name: '快手策略师', slug: 'kuaishou-strategist', division: '营销', emoji: '🎬', vibe: '精通快手平台运营策略', description: '精通快手平台运营策略', detail: '深入理解快手平台的下沉市场特性和老铁文化，精通快手短视频内容策划、直播运营、快手小店运营等，能帮助品牌在快手生态中实现精准触达和转化。' },
  { id: '267', name: '微博策略师', slug: 'weibo-strategist', division: '营销', emoji: '📢', vibe: '精通微博营销和话题运营', description: '精通微博营销和话题运营', detail: '精通微博热搜机制、话题运营、粉丝经济、KOL合作等微博营销核心能力，能帮助品牌通过微博实现话题引爆、口碑传播和舆情管理。' },
  { id: '268', name: '小红书专家', slug: 'xiaohongshu-specialist', division: '营销', emoji: '📕', vibe: '精通小红书种草和内容营销', description: '精通小红书种草和内容营销', detail: '深入理解小红书社区调性和用户消费决策路径，精通种草笔记策划、达人合作、品牌号运营、小红书搜索优化等，能帮助品牌在小红书实现高效种草转化。' },
  { id: '269', name: '知乎策略师', slug: 'zhihu-strategist', division: '营销', emoji: '💡', vibe: '精通知乎内容营销和知识付费', description: '精通知乎内容营销和知识付费', detail: '深入理解知乎社区的专业调性和内容生态，精通知乎问答营销、专栏内容策划、知乎好物推荐、知识付费产品设计等，能帮助品牌在知乎建立专业权威形象。' },
  { id: '270', name: '微信公众号运营', slug: 'wechat-official-account', division: '营销', emoji: '💬', vibe: '精通微信公众号内容运营', description: '精通微信公众号内容运营', detail: '精通微信公众号内容策划、排版设计、用户增长、菜单配置、小程序联动等运营全链路，能帮助品牌打造高质量的微信内容阵地，实现用户的深度触达和留存。' },
  { id: '271', name: 'Reddit社区运营', slug: 'reddit-community-builder', division: '营销', emoji: '🌐', vibe: '精通Reddit社区建设和运营', description: '精通Reddit社区建设和运营', detail: '深入理解Reddit社区规则和用户文化，精通Subreddit运营、AMA策划、Reddit广告投放、口碑管理等，能帮助品牌在Reddit社区建立真实的品牌口碑和用户信任。' },
  { id: '272', name: 'Twitter运营专家', slug: 'twitter-engager', division: '营销', emoji: '🐦', vibe: '精通Twitter内容运营和互动', description: '精通Twitter内容运营和互动', detail: '精通Twitter/X平台的内容策略、话题营销、KOL合作、Twitter Spaces音频互动等运营能力，能帮助品牌在Twitter上建立活跃的社交媒体影响力。' },
  { id: '273', name: 'Instagram运营专家', slug: 'instagram-curator', division: '营销', emoji: '📸', vibe: '精通Instagram视觉内容运营', description: '精通Instagram视觉内容运营', detail: '精通Instagram的视觉内容策划、Reels短视频运营、Stories互动设计、Instagram Shopping等，能帮助品牌打造极具视觉吸引力的Instagram内容矩阵。' },
  { id: '274', name: '多平台内容发布', slug: 'multi-platform-publisher', division: '营销', emoji: '📡', vibe: '精通多平台内容分发', description: '精通多平台内容分发', detail: '精通内容多平台分发策略，能根据不同平台的特性和用户群体，对内容进行适配和优化，实现一份内容在多个平台的高效分发和最大化曝光。' },
  { id: '275', name: '短视频剪辑教练', slug: 'short-video-editing-coach', division: '营销', emoji: '✂️', vibe: '精通短视频剪辑技巧', description: '精通短视频剪辑技巧', detail: '精通Premiere/Final Cut/剪映等短视频剪辑工具，精通节奏把控、转场设计、字幕排版、音乐选择等短视频剪辑核心技巧，能帮助创作者提升短视频内容质量。' },
  { id: '276', name: '百度SEO专家', slug: 'baidu-seo-specialist', division: '营销', emoji: '🔍', vibe: '精通百度搜索引擎优化', description: '精通百度搜索引擎优化', detail: '精通百度搜索引擎算法和排名机制，精通百度关键词研究、站内优化、百度站长平台、百度百科/知道等百度生态内容布局，能有效提升网站在百度的自然搜索排名。' },
  { id: '277', name: '应用商店优化师', slug: 'app-store-optimizer', division: '营销', emoji: '📲', vibe: '精通ASO应用商店优化', description: '精通ASO应用商店优化', detail: '精通App Store和各大安卓应用商店的排名算法，精通关键词优化、截图优化、评分管理、A/B测试等ASO核心技巧，能有效提升应用的下载量和排名。' },
  { id: '278', name: '跨境电商运营', slug: 'cross-border-ecommerce', division: '营销', emoji: '🌍', vibe: '精通跨境电商平台运营', description: '精通跨境电商平台运营', detail: '精通Amazon/Shopify/Lazada/Shopee等跨境电商平台运营，精通选品策略、Listing优化、FBA物流、跨境支付、多语言客服等跨境电商全链路能力。' },
  { id: '279', name: '直播电商教练', slug: 'livestream-commerce-coach', division: '营销', emoji: '📺', vibe: '精通直播带货技巧', description: '精通直播带货技巧', detail: '精通直播电商全流程，包括直播间搭建、主播培训、话术设计、选品策略、流量运营、数据分析等，能帮助品牌和主播打造高转化的直播带货体系。' },
  { id: '280', name: '视频优化专家', slug: 'video-optimization-specialist', division: '营销', emoji: '🎥', vibe: '精通视频内容优化', description: '精通视频内容优化', detail: '精通视频SEO优化、标题标签优化、缩略图设计、观看时长提升、推荐算法适配等视频优化核心能力，能帮助创作者和品牌最大化视频内容的传播效果。' },

  // === 专业领域 (Specialized) - 补充 ===
  { id: '281', name: '法律文档审查', slug: 'legal-document-review', division: '专业领域', emoji: '⚖️', vibe: '精通法律文档审查和风险识别', description: '精通法律文档审查和风险识别', detail: '精通合同、协议、条款等法律文档的审查流程，能快速识别文档中的法律风险点、不合理条款和潜在纠纷隐患，提供专业的修改建议和风险评估报告。' },
  { id: '282', name: '法律客户接待', slug: 'legal-client-intake', division: '专业领域', emoji: '👋', vibe: '精通法律咨询服务接待流程', description: '精通法律咨询服务接待流程', detail: '精通法律咨询的客户接待和初步评估流程，能高效收集案件信息、评估案件可行性、匹配合适的律师资源、制定初步服务方案，提升客户体验和案件转化率。' },
  { id: '283', name: '法律计费追踪', slug: 'legal-billing-time-tracking', division: '专业领域', emoji: '⏱️', vibe: '精通法律服务计费管理', description: '精通法律服务计费管理', detail: '精通法律服务的工时记录、费用核算、账单生成、客户对账等计费管理流程，能确保计费的准确性和及时性，优化律所的收入管理效率。' },
  { id: '284', name: '应付账款代理', slug: 'accounts-payable-agent', division: '专业领域', emoji: '💰', vibe: '精通应付账款管理', description: '精通应付账款管理', detail: '精通应付账款的全流程管理，包括发票接收、三单匹配、付款审批、付款执行、账务核对等，能确保付款流程准确高效，维护良好的供应商关系。' },
  { id: '285', name: '贷款审批助理', slug: 'loan-officer-assistant', division: '专业领域', emoji: '🏦', vibe: '精通贷款审批流程', description: '精通贷款审批流程', detail: '精通贷款申请的受理、资料审核、信用评估、风险筛查、审批决策辅助等全流程，能高效处理贷款申请，确保审批的准确性和合规性。' },
  { id: '286', name: '首席财务官', slug: 'chief-financial-officer', division: '专业领域', emoji: '💼', vibe: '精通企业财务战略管理', description: '精通企业财务战略管理', detail: '具备全面的企业财务管理能力，精通财务战略规划、资本结构优化、投资决策分析、投资者关系管理、风险控制等CFO核心职能，为企业的财务健康和可持续发展提供战略指导。' },
  { id: '287', name: '员工入职顾问', slug: 'hr-onboarding', division: '专业领域', emoji: '👥', vibe: '精通员工入职培训流程', description: '精通员工入职培训流程', detail: '精通新员工入职的全流程设计和执行，包括入职通知、资料准备、入职培训、导师分配、融入跟踪等，能帮助新员工快速适应组织文化并投入工作。' },
  { id: '288', name: '招聘专家', slug: 'recruitment-specialist', division: '专业领域', emoji: '🎯', vibe: '精通人才招聘和筛选', description: '精通人才招聘和筛选', detail: '精通人才招聘全流程，包括职位分析、招聘渠道管理、简历筛选、面试评估、背景调查、Offer谈判等，能高效为企业选拔和吸引优秀人才。' },
  { id: '289', name: '组织心理学家', slug: 'organizational-psychologist', division: '专业领域', emoji: '🧠', vibe: '精通组织行为和员工心理', description: '精通组织行为和员工心理', detail: '精通组织行为学理论和应用，能进行员工满意度调研、组织氛围诊断、领导力评估、员工心理健康干预等，帮助组织提升员工敬业度和团队效能。' },
  { id: '290', name: '客服专家', slug: 'customer-service', division: '专业领域', emoji: '📞', vibe: '精通客户服务和投诉处理', description: '精通客户服务和投诉处理', detail: '精通客户服务体系建设和管理，精通多渠道客户沟通、投诉处理、满意度提升、服务流程优化等核心能力，能帮助企业打造卓越的客户服务体验。' },
  { id: '291', name: '客户成功经理', slug: 'customer-success-manager', division: '专业领域', emoji: '🤝', vibe: '精通客户关系维护和续约', description: '精通客户关系维护和续约', detail: '精通客户成功方法论，能制定客户健康度评估体系、续费策略、增购方案、客户分层运营等，确保客户持续获得产品价值并实现业务增长。' },
  { id: '292', name: '酒店宾客服务', slug: 'hospitality-guest-services', division: '专业领域', emoji: '🏨', vibe: '精通酒店宾客服务管理', description: '精通酒店宾客服务管理', detail: '精通酒店前厅、客房、餐饮等宾客服务全流程管理，精通服务标准制定、员工培训、客户投诉处理、VIP接待等，能帮助酒店打造卓越的宾客服务体验。' },
  { id: '293', name: '销售拓展专家', slug: 'sales-outreach', division: '专业领域', emoji: '📈', vibe: '精通销售外呼和客户开发', description: '精通销售外呼和客户开发', detail: '精通电话销售、邮件外联、LinkedIn拓展等客户开发方式，能设计高效的外呼话术、跟进策略、客户分级方法，为销售团队持续输送高质量商机。' },
  { id: '294', name: '零售退换货处理', slug: 'retail-customer-returns', division: '专业领域', emoji: '🛒', vibe: '精通零售退换货流程', description: '精通零售退换货流程', detail: '精通零售行业的退换货政策制定、退货流程管理、逆向物流处理、退款结算、客户沟通等，能在控制成本的同时维护客户满意度和品牌声誉。' },
  { id: '295', name: '数据整合代理', slug: 'data-consolidation-agent', division: '专业领域', emoji: '📊', vibe: '精通数据整合和清洗', description: '精通数据整合和清洗', detail: '精通多源异构数据的整合和清洗，能处理数据格式转换、重复数据去重、缺失值填充、数据标准化等任务，确保数据的一致性和可用性。' },
  { id: '296', name: '报告分发代理', slug: 'report-distribution-agent', division: '专业领域', emoji: '📋', vibe: '精通报告自动生成和分发', description: '精通报告自动生成和分发', detail: '精通报告的自动生成、格式化、分发流程，能根据数据源自动创建可视化报告，并通过邮件、企业微信、飞书等渠道自动分发给相关受众。' },
  { id: '297', name: '数据隐私官', slug: 'data-privacy-officer', division: '专业领域', emoji: '🔐', vibe: '精通数据隐私保护合规', description: '精通数据隐私保护合规', detail: '精通GDPR/个人信息保护法等数据隐私法规，能制定数据隐私政策、进行隐私影响评估(PIA)、管理数据主体权利请求、开展隐私合规审计。' },
  { id: '298', name: '政府数字预销售顾问', slug: 'government-digital-presales-consultant', division: '专业领域', emoji: '🏛️', vibe: '精通政府数字化项目', description: '精通政府数字化项目', detail: '精通政府数字化项目的招投标流程、方案设计、技术选型、POC演示等预销售环节，理解电子政务、数字政府等领域的业务需求和技术趋势。' },
  { id: '299', name: 'FedRAMP合规专家', slug: 'fedramp-rmf-compliance', division: '专业领域', emoji: '🛡️', vibe: '精通FedRAMP安全合规', description: '精通FedRAMP安全合规', detail: '精通FedRAMP/RMF安全合规框架，能帮助云服务提供商和联邦机构完成安全评估、安全控制实施、持续监控、授权运营等FedRAMP合规全流程。' },
  { id: '300', name: '拨款撰写专家', slug: 'grant-writer', division: '专业领域', emoji: '📝', vibe: '精通政府拨款申请撰写', description: '精通政府拨款申请撰写', detail: '精通各类政府拨款和基金的申请流程和撰写技巧，能撰写高质量的拨款申请书、项目计划书、预算说明等，显著提升拨款申请的成功率。' },
  { id: '301', name: '语言翻译专家', slug: 'language-translator', division: '专业领域', emoji: '🌐', vibe: '精通多语言翻译', description: '精通多语言翻译', detail: '精通多语言翻译和本地化，具备深厚的双语能力，精通技术文档翻译、营销文案本地化、法律文件翻译等专业翻译领域，确保翻译的准确性和文化适配性。' },
  { id: '302', name: '文化智能策略师', slug: 'cultural-intelligence-strategist', division: '专业领域', emoji: '🌍', vibe: '精通跨文化商务沟通', description: '精通跨文化商务沟通', detail: '精通不同文化背景下的商务沟通和管理策略，能帮助跨国团队理解文化差异、优化沟通方式、避免文化冲突，提升跨文化协作效率。' },
  { id: '303', name: '供应链策略师', slug: 'supply-chain-strategist', division: '专业领域', emoji: '🔗', vibe: '精通供应链管理和优化', description: '精通供应链管理和优化', detail: '精通供应链战略规划、供应商管理、库存优化、物流网络设计、需求预测等供应链核心能力，能帮助企业构建高效、韧性、可持续的供应链体系。' },
  { id: '304', name: '运营经理', slug: 'operations-manager', division: '专业领域', emoji: '⚙️', vibe: '精通企业运营管理', description: '精通企业运营管理', detail: '精通企业运营流程设计和优化，能管理日常运营、制定运营指标、优化资源配置、推动流程改进，确保企业运营高效顺畅。' },
  { id: '305', name: '变革管理顾问', slug: 'change-management-consultant', division: '专业领域', emoji: '🔄', vibe: '精通组织变革管理', description: '精通组织变革管理', detail: '精通组织变革管理方法论(如Kotter/ADKAR)，能帮助组织规划变革策略、管理利益相关者、推动文化转型、降低变革阻力，确保变革成功落地。' },
  { id: '306', name: '企业培训设计师', slug: 'corporate-training-designer', division: '专业领域', emoji: '🎓', vibe: '精通企业培训课程设计', description: '精通企业培训课程设计', detail: '精通企业培训需求分析、课程体系设计、教学方法选择、培训效果评估等全流程，能设计和开发高质量的企业培训课程，提升员工能力和组织绩效。' },
  { id: '307', name: '简历优化专家', slug: 'resume-tailor', division: '专业领域', emoji: '📄', vibe: '精通简历优化和求职指导', description: '精通简历优化和求职指导', detail: '精通简历撰写和优化技巧，能根据不同行业和职位的要求定制简历内容，优化关键词匹配、项目描述、成果量化等，帮助求职者获得面试机会。' },
  { id: '308', name: '个人成长导师', slug: 'personal-growth-mentor', division: '专业领域', emoji: '🌱', vibe: '精通个人成长和职业发展', description: '精通个人成长和职业发展', detail: '精通个人成长方法论和职业发展策略，能帮助个人制定成长目标、培养关键技能、建立职业品牌、规划职业路径，实现职业和个人的持续成长。' },
  { id: '309', name: '企业架构师', slug: 'enterprise-architect', division: '专业领域', emoji: '🏗️', vibe: '精通企业IT架构设计', description: '精通企业IT架构设计', detail: '精通企业架构框架(TOGAF/Zachman)，能设计与业务战略对齐的IT架构，包括应用架构、数据架构、技术架构等，推动企业数字化转型和IT治理。' },
  { id: '310', name: 'AI智能体编排师', slug: 'agents-orchestrator', division: '专业领域', emoji: '🤖', vibe: '精通AI智能体编排和协调', description: '精通AI智能体编排和协调', detail: '精通多智能体系统的设计和编排，能规划智能体的职责分工、通信协议、任务调度、协作策略等，构建高效协作的AI智能体集群完成复杂任务。' },

  // === 工程 (Engineering) - 补充 ===
  { id: '311', name: 'CMS开发工程师', slug: 'cms-developer', division: '工程', emoji: '⚙️', vibe: '精通内容管理系统开发', description: '精通内容管理系统开发', detail: '精通WordPress/Drupal/Joomla等CMS系统的开发和定制，能进行主题开发、插件开发、内容模型设计、多站点管理等CMS核心开发工作。' },
  { id: '312', name: 'WordPress性能专家', slug: 'wordpress-performance', division: '工程', emoji: '⚡', vibe: '精通WordPress性能优化', description: '精通WordPress性能优化', detail: '精通WordPress性能瓶颈分析和优化，包括数据库查询优化、缓存策略、CDN配置、图片优化、PHP性能调优等，能将WordPress站点的加载速度提升数倍。' },
  { id: '313', name: 'WordPress电商专家', slug: 'wordpress-shopping-cart', division: '工程', emoji: '🛒', vibe: '精通WooCommerce电商开发', description: '精通WooCommerce电商开发', detail: '精通WooCommerce电商插件的开发和定制，能进行商品管理、支付集成、物流对接、会员体系、营销活动等电商功能开发，打造高性能的WordPress电商网站。' },
  { id: '314', name: '代码审查专家', slug: 'code-reviewer', division: '工程', emoji: '🔍', vibe: '精通代码质量审查和最佳实践', description: '精通代码质量审查和最佳实践', detail: '精通多语言的代码审查最佳实践，能发现代码中的安全漏洞、性能瓶颈、设计缺陷、可维护性问题，提供有建设性的改进建议，帮助团队提升代码质量。' },
  { id: '315', name: 'Git工作流大师', slug: 'git-workflow-master', division: '工程', emoji: '🔀', vibe: '精通Git工作流和团队协作', description: '精通Git工作流和团队协作', detail: '精通Git Flow/GitHub Flow/Trunk-Based等Git工作流模式，精通分支管理、代码合并策略、版本标签、冲突解决等Git高级操作，能为团队设计高效的Git协作流程。' },
  { id: '316', name: '技术文档工程师', slug: 'technical-writer', division: '工程', emoji: '📝', vibe: '精通技术文档撰写', description: '精通技术文档撰写', detail: '精通技术文档的编写规范和最佳实践，能撰写API文档、用户手册、架构设计文档、运维指南、发布说明等各类技术文档，确保文档准确、清晰、易维护。' },
  { id: '317', name: '国际化工程师', slug: 'i18n-engineer', division: '工程', emoji: '🌍', vibe: '精通网站和应用国际化', description: '精通网站和应用国际化', detail: '精通国际化(i18n)和本地化(l10n)技术实现，能设计多语言架构、处理字符编码、适配不同地区的日期/货币/数字格式、管理翻译文件，确保产品在全球市场的无缝体验。' },
  { id: '318', name: '微信小程序开发者', slug: 'wechat-mini-program-developer', division: '工程', emoji: '📱', vibe: '精通微信小程序开发', description: '精通微信小程序开发', detail: '精通微信小程序的开发框架和API，熟练掌握WXML/WXSS/JavaScript，精通小程序的组件化开发、云开发、支付集成、分享裂变等核心能力。' },
  { id: '319', name: '飞书集成开发者', slug: 'feishu-integration-developer', division: '工程', emoji: '💬', vibe: '精通飞书应用集成开发', description: '精通飞书应用集成开发', detail: '精通飞书开放平台的API和SDK，能开发飞书机器人、审批流程集成、日历/文档/会议等办公套件集成、自定义应用等，提升企业办公效率。' },
  { id: '320', name: '软件架构师', slug: 'software-architect', division: '工程', emoji: '🏛️', vibe: '精通软件架构设计和系统设计', description: '精通软件架构设计和系统设计', detail: '具备全面的软件架构设计能力，精通微服务/事件驱动/六边形等架构模式，能进行系统需求分析、架构选型、技术规范制定、架构评审等，确保系统的可扩展性、可维护性和高可用性。' },
  { id: '321', name: '事件响应指挥官', slug: 'incident-response-commander', division: '工程', emoji: '🚨', vibe: '精通安全事件应急响应', description: '精通安全事件应急响应', detail: '精通安全事件的检测、分析、遏制、根除和恢复全流程，能指挥跨团队的应急响应行动，制定事件响应预案，进行事后复盘和改进，降低安全事件的影响。' },
  { id: '322', name: '数据库可靠性工程师', slug: 'database-reliability-engineer', division: '工程', emoji: '🗄️', vibe: '精通数据库高可用保障', description: '精通数据库高可用保障', detail: '精通数据库高可用架构设计，包括主从复制、读写分离、分库分表、备份恢复、故障切换等，能保障数据库服务的稳定性和数据的完整性。' },
  { id: '323', name: 'FinOps工程师', slug: 'finops-engineer', division: '工程', emoji: '💰', vibe: '精通云成本优化管理', description: '精通云成本优化管理', detail: '精通FinOps方法论和云成本管理，能进行云资源使用分析、成本归因、预算告警、预留实例优化、资源右-sizing等，帮助企业实现云支出的可视化和最优化。' },
  { id: '324', name: '支付账单工程师', slug: 'payments-billing-engineer', division: '工程', emoji: '💳', vibe: '精通支付和计费系统开发', description: '精通支付和计费系统开发', detail: '精通支付网关集成、订阅计费、发票生成、账单对账、退款处理等支付和计费系统的核心模块开发，确保支付流程的安全性、准确性和高可用性。' },

  // === 游戏开发 (Game Development) - 补充 ===
  { id: '325', name: '游戏制作人', slug: 'game-producer', division: '游戏开发', emoji: '🎮', vibe: '精通游戏项目管理和制作', description: '精通游戏项目管理和制作', detail: '精通游戏项目的全生命周期管理，包括立项评估、团队组建、进度管理、预算控制、发行协调等，能确保游戏项目按时按质交付并达到商业目标。' },
  { id: '326', name: '游戏特效师', slug: 'vfx-artist', division: '游戏开发', emoji: '✨', vibe: '精通游戏视觉特效制作', description: '精通游戏视觉特效制作', detail: '精通Unity/Unreal Engine的特效系统，熟练掌握粒子系统、Shader编写、特效动画制作等技术，能为游戏制作震撼的技能特效、环境特效和UI特效。' },
  { id: '327', name: '游戏概念设计师', slug: 'concept-artist', division: '游戏开发', emoji: '🎨', vibe: '精通游戏概念美术设计', description: '精通游戏概念美术设计', detail: '具备出色的手绘和数字绘画能力，精通Photoshop/Procreate等工具，能为游戏角色、场景、道具、界面等创作高质量的概念设计稿，定义游戏的视觉风格。' },
  { id: '328', name: '游戏UI设计师', slug: 'ui-game-designer', division: '游戏开发', emoji: '🖥️', vibe: '精通游戏界面设计', description: '精通游戏界面设计', detail: '精通游戏UI设计规范和交互模式，能设计游戏主界面、HUD、菜单系统、背包系统、战斗界面等游戏UI组件，确保界面美观且操作流畅。' },
  { id: '329', name: '游戏编剧', slug: 'game-writer', division: '游戏开发', emoji: '📖', vibe: '精通游戏剧情和对话编写', description: '精通游戏剧情和对话编写', detail: '精通游戏叙事设计和对话编写，能创作引人入胜的游戏剧情、角色对话、世界观设定、任务文本等，通过文字赋予游戏深刻的情感和沉浸感。' },
  { id: '330', name: '游戏本地化专家', slug: 'localization-specialist', division: '游戏开发', emoji: '🌐', vibe: '精通游戏本地化翻译', description: '精通游戏本地化翻译', detail: '精通游戏本地化全流程，包括界面文本翻译、剧情配音脚本、文化适配、术语管理、本地化测试等，确保游戏在不同语言市场都能提供优秀的用户体验。' },
  { id: '331', name: '游戏商业化设计师', slug: 'game-monetization-designer', division: '游戏开发', emoji: '💰', vibe: '精通游戏付费设计', description: '精通游戏付费设计', detail: '精通游戏商业化模式设计，包括内购系统、战令系统、抽卡机制、广告变现、订阅服务等，能在保持良好玩家体验的同时最大化游戏的商业收入。' },
  { id: '332', name: '游戏数据分析师', slug: 'game-analytics-specialist', division: '游戏开发', emoji: '📊', vibe: '精通游戏数据分析', description: '精通游戏数据分析', detail: '精通游戏数据分析工具和方法，能进行玩家行为分析、留存分析、付费分析、关卡漏斗分析等，通过数据洞察驱动游戏设计和运营决策的优化。' },
  { id: '333', name: '游戏社区经理', slug: 'community-manager', division: '游戏开发', emoji: '👥', vibe: '精通游戏社区运营', description: '精通游戏社区运营', detail: '精通游戏社区建设和运营策略，能管理Discord/贴吧/微博等社区渠道、策划社区活动、处理玩家反馈、维护KOL关系，构建活跃健康的游戏社区生态。' },
  { id: '334', name: '游戏引擎工程师', slug: 'engine-programmer', division: '游戏开发', emoji: '🔧', vibe: '精通游戏引擎开发', description: '精通游戏引擎开发', detail: '精通游戏引擎底层开发，包括渲染管线、物理引擎、音频系统、资源管理、脚本系统等核心模块的开发和优化，能为游戏项目提供高性能的底层技术支持。' },

  // === 地理信息 (GIS) - 补充 ===
  { id: '335', name: '地理空间数据工程师', slug: 'geospatial-data-engineer', division: '地理信息', emoji: '🗺️', vibe: '精通地理空间数据处理', description: '精通地理空间数据处理', detail: '精通地理空间数据的采集、存储、处理和分析，精通PostGIS/GeoServer/GDAL等地理空间数据工具，能构建可靠的空间数据管道和数据服务。' },
  { id: '336', name: 'LiDAR专家', slug: 'lidar-specialist', division: '地理信息', emoji: '📡', vibe: '精通激光雷达数据处理', description: '精通激光雷达数据处理', detail: '精通LiDAR点云数据的采集、处理、分类和建模，能进行三维地形生成、建筑物提取、森林资源调查、电力线路巡检等LiDAR应用，为空间分析提供高精度数据支撑。' },
  { id: '337', name: '地籍测量师', slug: 'cadastral-surveyor', division: '地理信息', emoji: '📐', vibe: '精通土地测量和地籍管理', description: '精通土地测量和地籍管理', detail: '精通地籍测量和土地权属管理，能进行界址点测量、地籍图绘制、土地面积计算、不动产登记等，确保土地信息的准确性和法律效力。' },
];

export { mockAgents };
